/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package khanzahmsanjungan;

import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;

public class DlgAmbilAntrian extends widget.Dialog {

    private final Connection koneksi = koneksiDB.condb();
    private final sekuel Sequel = new sekuel();
    private final validasi Valid = new validasi();
    private final String[] PREFIXHURUFAKTIF = koneksiDB.PREFIXHURUFAKTIF();

    private Map<String, Object> param = new HashMap<>();

    public DlgAmbilAntrian(java.awt.Frame parent, boolean id) {
        super(parent, id);
        initComponents();

        try (ResultSet rs = koneksi.createStatement().executeQuery(
            "select nama_instansi, alamat_instansi, kabupaten, propinsi, kontak, email from setting"
        )) {
            if (rs.next()) {
                param.put("namars", rs.getString("nama_instansi"));
                param.put("alamatrs", rs.getString("alamat_instansi"));
                param.put("kotars", rs.getString("kabupaten"));
                param.put("propinsirs", rs.getString("propinsi"));
                param.put("kontakrs", rs.getString("kontak"));
                param.put("emailrs", rs.getString("email"));
            }
        } catch (Exception e) {
            System.out.println("Notif : " + e);
        }

        panelTengah.remove(HurufA);
//        panelTengah.remove(HurufB);
//        panelTengah.remove(HurufC);
//        panelTengah.remove(HurufD);
//        panelTengah.remove(HurufE);
//        panelTengah.remove(HurufF);

        for (String huruf : PREFIXHURUFAKTIF) {
            switch (huruf) {
                case "A":
                    panelTengah.add(HurufA);
                    break;
//                case "B":
//                    panelTengah.add(HurufB);
//                    break;
//                case "C":
//                    panelTengah.add(HurufC);
//                    break;
//                case "D":
//                    panelTengah.add(HurufD);
//                    break;
//                case "E":
//                    panelTengah.add(HurufE);
//                    break;
//                case "F":
//                    panelTengah.add(HurufF);
//                    break;
            }
        }
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTengah = new widget.Panel();
        HurufA = new widget.MenuButton();
        panelBawah = new widget.Panel();
        btnKeluar = new widget.Button();
        panelAtas = new widget.Panel();
        flatLabel1 = new com.formdev.flatlaf.extras.components.FlatLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        panelTengah.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelTengah.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        panelTengah.setLayout(new java.awt.GridLayout());

        HurufA.setBackground(new java.awt.Color(0, 153, 153));
        HurufA.setForeground(new java.awt.Color(255, 255, 255));
        HurufA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/fingerprint.png"))); // NOI18N
        HurufA.setText("AMBIL ANTRIAN");
        HurufA.setButtonType(com.formdev.flatlaf.extras.components.FlatButton.ButtonType.roundRect);
        HurufA.setFont(new java.awt.Font("Inter", 1, 48)); // NOI18N
        HurufA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HurufAActionPerformed(evt);
            }
        });
        panelTengah.add(HurufA);

        getContentPane().add(panelTengah, java.awt.BorderLayout.CENTER);

        btnKeluar.setBackground(new java.awt.Color(240, 249, 255));
        btnKeluar.setForeground(new java.awt.Color(255, 33, 32));
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/exit.png"))); // NOI18N
        btnKeluar.setMnemonic('U');
        btnKeluar.setText("KELUAR");
        btnKeluar.setToolTipText("Alt+U");
        btnKeluar.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        btnKeluar.setIconTextGap(2);
        btnKeluar.setPreferredSize(new java.awt.Dimension(200, 75));
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        panelBawah.add(btnKeluar);

        getContentPane().add(panelBawah, java.awt.BorderLayout.PAGE_END);

        panelAtas.setMinimumSize(new java.awt.Dimension(500, 100));
        panelAtas.setPreferredSize(new java.awt.Dimension(500, 100));
        panelAtas.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 10));

        flatLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/logocokro (2).png"))); // NOI18N
        panelAtas.add(flatLabel1);

        getContentPane().add(panelAtas, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HurufAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HurufAActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        cetakAntrianHuruf("A");
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_HurufAActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        tampil();
    }//GEN-LAST:event_formWindowActivated

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.MenuButton HurufA;
    private widget.Button btnKeluar;
    private com.formdev.flatlaf.extras.components.FlatLabel flatLabel1;
    private widget.Panel panelAtas;
    private widget.Panel panelBawah;
    private widget.Panel panelTengah;
    // End of variables declaration//GEN-END:variables

    private void cetakAntrianHuruf(String prefix) {
        switch (prefix) {
            case "A":
                if (Sequel.executeRawSmc(
                    "insert into antriloketcetak_smc (nomor, tanggal, jam) values (concat('A', lpad(?, greatest(length(substring(nomor, 2)), 3), '0')), current_date(), current_time())",
                    String.valueOf(Integer.parseInt(HurufA.getText().substring(HurufA.getText().indexOf("(") + 2, HurufA.getText().length() - 1)) + 1)
                )) {
                    param.put("logo", Sequel.cariGambar("select logo from setting"));
                    Valid.printReportSmc("rptAntriLoketAPM.jasper", "report", "::[ Antrian Loket ]::", param, koneksiDB.PRINTER_ANTRIAN(), 1,
                        "select date_format(tanggal, '%d-%m-%Y') as tanggal, nomor, jam from " +
                        "antriloketcetak_smc where left(nomor, 1) = 'A' and tanggal = current_date() order by nomor desc limit 1");
                }
                break;
//            case "B":
//                if (Sequel.executeRawSmc(
//                    "insert into antriloketcetak_smc (nomor, tanggal, jam) values (concat('B', lpad(?, greatest(length(substring(nomor, 2)), 3), '0')), current_date(), current_time())",
//                    String.valueOf(Integer.parseInt(HurufB.getText().substring(HurufB.getText().indexOf("(") + 2, HurufB.getText().length() - 1)) + 1)
//                )) {
//                    param.put("logo", Sequel.cariGambar("select logo from setting"));
//                    Valid.printReportSmc("rptAntriLoketAPM.jasper", "report", "::[ Antrian Loket ]::", param, koneksiDB.PRINTER_ANTRIAN(), 1,
//                        "select date_format(tanggal, '%d-%m-%Y') as tanggal, nomor, jam from " +
//                        "antriloketcetak_smc where left(nomor, 1) = 'B' and tanggal = current_date() order by nomor desc limit 1");
//                }
//                break;
//            case "C":
//                if (Sequel.executeRawSmc(
//                    "insert into antriloketcetak_smc (nomor, tanggal, jam) values (concat('C', lpad(?, greatest(length(substring(nomor, 2)), 3), '0')), current_date(), current_time())",
//                    String.valueOf(Integer.parseInt(HurufC.getText().substring(HurufC.getText().indexOf("(") + 2, HurufC.getText().length() - 1)) + 1)
//                )) {
//                    param.put("logo", Sequel.cariGambar("select logo from setting"));
//                    Valid.printReportSmc("rptAntriLoketAPM.jasper", "report", "::[ Antrian Loket ]::", param, koneksiDB.PRINTER_ANTRIAN(), 1,
//                        "select date_format(tanggal, '%d-%m-%Y') as tanggal, nomor, jam from " +
//                        "antriloketcetak_smc where left(nomor, 1) = 'C' and tanggal = current_date() order by nomor desc limit 1");
//                }
//                break;
//            case "D":
//                if (Sequel.executeRawSmc(
//                    "insert into antriloketcetak_smc (nomor, tanggal, jam) values (concat('D', lpad(?, greatest(length(substring(nomor, 2)), 3), '0')), current_date(), current_time())",
//                    String.valueOf(Integer.parseInt(HurufD.getText().substring(HurufD.getText().indexOf("(") + 2, HurufD.getText().length() - 1)) + 1)
//                )) {
//                    param.put("logo", Sequel.cariGambar("select logo from setting"));
//                    Valid.printReportSmc("rptAntriLoketAPM.jasper", "report", "::[ Antrian Loket ]::", param, koneksiDB.PRINTER_ANTRIAN(), 1,
//                        "select date_format(tanggal, '%d-%m-%Y') as tanggal, nomor, jam from " +
//                        "antriloketcetak_smc where left(nomor, 1) = 'D' and tanggal = current_date() order by nomor desc limit 1");
//                }
//                break;
//            case "E":
//                if (Sequel.executeRawSmc(
//                    "insert into antriloketcetak_smc (nomor, tanggal, jam) values (concat('E', lpad(?, greatest(length(substring(nomor, 2)), 3), '0')), current_date(), current_time())",
//                    String.valueOf(Integer.parseInt(HurufE.getText().substring(HurufE.getText().indexOf("(") + 2, HurufE.getText().length() - 1)) + 1)
//                )) {
//                    param.put("logo", Sequel.cariGambar("select logo from setting"));
//                    Valid.printReportSmc("rptAntriLoketAPM.jasper", "report", "::[ Antrian Loket ]::", param, koneksiDB.PRINTER_ANTRIAN(), 1,
//                        "select date_format(tanggal, '%d-%m-%Y') as tanggal, nomor, jam from " +
//                        "antriloketcetak_smc where left(nomor, 1) = 'E' and tanggal = current_date() order by nomor desc limit 1");
//                }
//                break;
//            case "F":
//                if (Sequel.executeRawSmc(
//                    "insert into antriloketcetak_smc (nomor, tanggal, jam) values (concat('F', lpad(?, greatest(length(substring(nomor, 2)), 3), '0')), current_date(), current_time())",
//                    String.valueOf(Integer.parseInt(HurufF.getText().substring(HurufF.getText().indexOf("(") + 2, HurufF.getText().length() - 1)) + 1)
//                )) {
//                    param.put("logo", Sequel.cariGambar("select logo from setting"));
//                    Valid.printReportSmc("rptAntriLoketAPM.jasper", "report", "::[ Antrian Loket ]::", param, koneksiDB.PRINTER_ANTRIAN(), 1,
//                        "select date_format(tanggal, '%d-%m-%Y') as tanggal, nomor, jam from " +
//                        "antriloketcetak_smc where left(nomor, 1) = 'F' and tanggal = current_date() order by nomor desc limit 1");
//                }
//                break;
        }
        tampil();
    }

    private void tampil() {
        for (String huruf : PREFIXHURUFAKTIF) {
            switch (huruf) {
                case "A":
                    HurufA.setText("AMBIL ANTRIAN (" + Sequel.cariIsiSmc("select ifnull(max(nomor), 'A000') from antriloketcetak_smc where tanggal = current_date() and left(nomor, 1) = 'A'") + ")");
                    break;
//                case "B":
//                    HurufB.setText("PASIEN P2KM (" + Sequel.cariIsiSmc("select ifnull(max(nomor), 'B000') from antriloketcetak_smc where tanggal = current_date() and left(nomor, 1) = 'B'") + ")");
//                    break;
//                case "C":
//                    HurufC.setText("PASIEN UMUM (" + Sequel.cariIsiSmc("select ifnull(max(nomor), 'C000') from antriloketcetak_smc where tanggal = current_date() and left(nomor, 1) = 'C'") + ")");
//                    break;
//                case "D":
//                    HurufD.setText("ANTRIAN D (" + Sequel.cariIsiSmc("select ifnull(max(nomor), 'D000') from antriloketcetak_smc where tanggal = current_date() and left(nomor, 1) = 'D'") + ")");
//                    break;
//                case "E":
//                    HurufE.setText("ANTRIAN E (" + Sequel.cariIsiSmc("select ifnull(max(nomor), 'E000') from antriloketcetak_smc where tanggal = current_date() and left(nomor, 1) = 'E'") + ")");
//                    break;
//                case "F":
//                    HurufF.setText("ANTRIAN F (" + Sequel.cariIsiSmc("select ifnull(max(nomor), 'F000') from antriloketcetak_smc where tanggal = current_date() and left(nomor, 1) = 'F'") + ")");
//                    break;
            }
        }
    }
}
