/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package khanzahmsanjungan;

import AESsecurity.EnkripsiAES;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileReader;
import java.sql.Connection;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.Map;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

public class DlgAmbilAntrianFarmasi extends widget.Dialog {
    private final Connection koneksi = koneksiDB.condb();
    private final sekuel Sequel = new sekuel();
    private final validasi Valid = new validasi();
    private final String templateAntrian = "<html><body><center>TEKAN<br>⟶&nbsp;&nbsp;DISINI&nbsp;&nbsp;⟵<br>(%s)</center></body></html>";
    private String printerAntrian = "";
    private int printJumlahAntrianFarmasi = 0;

    private Map<String, Object> param = new HashMap<>();

    public DlgAmbilAntrianFarmasi(java.awt.Frame parent, boolean id) {
        super(parent, id);
        initComponents();

        try (ResultSet rs = koneksi.createStatement().executeQuery(
            "select nama_instansi, alamat_instansi, kabupaten, propinsi, kontak, email from setting"
        )) {
            if (rs.next()) {
                param.put("namars", rs.getString("nama_instansi"));
                param.put("alamatrs", rs.getString("alamat_instansi"));
                param.put("kotars", rs.getString("kabupaten"));
                param.put("propinsirs", rs.getString("propinsi"));
                param.put("kontakrs", rs.getString("kontak"));
                param.put("emailrs", rs.getString("email"));
            }
        } catch (Exception e) {
            System.out.println("Notif : " + e);
        }

        InputMap input = rootPane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap action = rootPane.getActionMap();

        input.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "ESCAPE");
        action.put("ESCAPE", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });

        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelAtas = new widget.Panel();
        judul = new widget.Label();
        panelTengah = new widget.Panel();
        AmbilAntrian = new widget.MenuButton();
        tanggal = new widget.Label();
        panelBawah = new widget.Panel();
        btnKeluar = new widget.Button();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        panelAtas.setPreferredSize(new java.awt.Dimension(80, 80));

        judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul.setText("ANTRIAN RESEP FARMASI");
        judul.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        judul.setFont(new java.awt.Font("Inter", 1, 60)); // NOI18N
        judul.setPreferredSize(new java.awt.Dimension(800, 80));
        panelAtas.add(judul);

        getContentPane().add(panelAtas, java.awt.BorderLayout.PAGE_START);

        panelTengah.setLayout(new java.awt.GridBagLayout());

        AmbilAntrian.setText("<html>\n<body>\n<center>\n⟶ KLIK DISINI ⟵<br>(0001)\n</center>\n</body>\n</html>"); // NOI18N
        AmbilAntrian.setActionCommand("<html>\n<body>\n<center>\n⟶ TEKAN DISINI ⟵<br>(0001)\n</center>\n</body>\n</html>");
        AmbilAntrian.setFont(new java.awt.Font("Inter", 1, 120)); // NOI18N
        AmbilAntrian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmbilAntrianActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelTengah.add(AmbilAntrian, gridBagConstraints);

        tanggal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tanggal.setText("Tanggal"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panelTengah.add(tanggal, gridBagConstraints);

        getContentPane().add(panelTengah, java.awt.BorderLayout.CENTER);

        btnKeluar.setBackground(new java.awt.Color(240, 249, 255));
        btnKeluar.setForeground(new java.awt.Color(255, 78, 21));
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        btnKeluar.setToolTipText("Keluar");
        btnKeluar.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        btnKeluar.setIconTextGap(2);
        btnKeluar.setPreferredSize(new java.awt.Dimension(40, 40));
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        panelBawah.add(btnKeluar);

        getContentPane().add(panelBawah, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AmbilAntrianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmbilAntrianActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        cetakAntrian();
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_AmbilAntrianActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        loadPengaturanAPM();
        tampil();
    }//GEN-LAST:event_formWindowActivated

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.MenuButton AmbilAntrian;
    private widget.Button btnKeluar;
    private widget.Label judul;
    private widget.Panel panelAtas;
    private widget.Panel panelBawah;
    private widget.Panel panelTengah;
    private widget.Label tanggal;
    // End of variables declaration//GEN-END:variables

    private void cetakAntrian() {
        if (Sequel.executeRawSmc("insert into antriloketfarmasi_smc (nomor, tanggal, jam) values (lpad(?, greatest(length(nomor), 4), '0'), current_date(), current_time())",
            String.valueOf(Integer.parseInt(AmbilAntrian.getText().substring(AmbilAntrian.getText().indexOf("(") + 1, AmbilAntrian.getText().indexOf(")"))))
        )) {
            Valid.printReportSmc("rptAntriFarmasiAPM.jasper", "report", "::[ Antrian Farmasi ]::", param, printerAntrian, printJumlahAntrianFarmasi,
                "select date_format(tanggal, '%d-%m-%Y') as tanggal, nomor, jam from antriloketfarmasi_smc where tanggal = current_date() order by nomor desc limit 1");
            Valid.popupInfoDialog("Silahkan ambil antrian anda..!!", 3);
        }
        tampil();
    }

    private void tampil() {
        tanggal.setText("Tanggal " + LocalDate.now());
        AmbilAntrian.setText(String.format(templateAntrian,
            Sequel.cariIsiSmc("select lpad(ifnull(max(convert(nomor, unsigned)), 0) + 1, greatest(length(ifnull(nomor, 0)), 4), '0') from antriloketfarmasi_smc where tanggal = current_date()")
        ));
    }

    private void loadPengaturanAPM() {
        if (new File("./cache/pengaturanapmsmc.iyem").isFile()) {
            try (FileReader fr = new FileReader("./cache/pengaturanapmsmc.iyem")) {
                final ObjectMapper mapper = new ObjectMapper();
                final JsonNode root = mapper.readTree(fr).path("pengaturanapmsmc");
                final JsonNode decrypted = mapper.readTree(EnkripsiAES.decrypt(root.asText()));

                if (decrypted.hasNonNull("printerAntrian")) {
                    printerAntrian = decrypted.path("printerAntrian").asText();
                }

                if (decrypted.hasNonNull("printJumlahAntrianFarmasi")) {
                    printJumlahAntrianFarmasi = decrypted.path("printJumlahAntrianFarmasi").asInt(0);
                }
            } catch (Exception e) {
                System.out.println("Notif : " + e);
            }
        } else {
            printerAntrian = koneksiDB.PRINTER_ANTRIAN();
            printJumlahAntrianFarmasi = koneksiDB.PRINTJUMLAHANTRIANFARMASI();
        }
    }
}
