package khanzahmsanjungan;

import fungsi.koneksiDB;
import fungsi.validasi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public final class DlgCariPoli2 extends widget.Dialog {
    private final DefaultTableModel tabMode;
    private final validasi Valid = new validasi();
    private final Connection koneksi = koneksiDB.condb();

    public DlgCariPoli2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        tabMode = new DefaultTableModel(null, new Object[] {"P", "Kode Unit", "Nama Unit"}) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return colIndex == 0;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 0) {
                    return Boolean.class;
                }

                return String.class;
            }
        };
        tbPoli.setModel(tabMode);
        tbPoli.getColumnModel().getColumn(0).setPreferredWidth(40);
        tbPoli.getColumnModel().getColumn(1).setPreferredWidth(100);
        tbPoli.getColumnModel().getColumn(2).setPreferredWidth(500);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Scroll = new widget.ScrollPane();
        tbPoli = new widget.Table();
        panelBawah = new widget.Panel();
        btnKeluar = new widget.Button();

        tbPoli.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Scroll.setViewportView(tbPoli);

        getContentPane().add(Scroll, java.awt.BorderLayout.CENTER);

        panelBawah.setName("panelBawah"); // NOI18N
        panelBawah.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        btnKeluar.setBackground(new java.awt.Color(255, 255, 255));
        btnKeluar.setForeground(new java.awt.Color(255, 23, 26));
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/exit.png"))); // NOI18N
        btnKeluar.setText("KELUAR");
        btnKeluar.setName("btnKeluar"); // NOI18N
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        panelBawah.add(btnKeluar);

        getContentPane().add(panelBawah, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.ScrollPane Scroll;
    private widget.Button btnKeluar;
    private widget.Panel panelBawah;
    private widget.Table tbPoli;
    // End of variables declaration//GEN-END:variables

    public void tampil() {
        Valid.tabelKosongSmc(tabMode);
        try (ResultSet rs = koneksi.createStatement().executeQuery(
            "select p.kd_poli, p.nm_poli from poliklinik as p where p.status = '1' order by p.nm_poli"
        )) {
            while (rs.next()) {
                tabMode.addRow(new Object[] {false, rs.getString("kd_poli"), rs.getString("nm_poli")});
            }
        } catch (Exception e) {
            System.out.println("Notif : " + e);
        }
    }

    public void setSelectedRows(List<String> list) {
        for (String poli : list) {
            for (int i = 0; i < tabMode.getRowCount(); i++) {
                if (poli.equals((String) tabMode.getValueAt(i, 1))) {
                    tabMode.setValueAt(true, i, 0);
                    break;
                }
            }
        }
    }

    public boolean hasSelection() {
        return tbPoli.getSelectedRow() >= 0 || countSelected() > 0;
    }

    public Object getSelectedRow(int column) {
        return tbPoli.getValueAt(tbPoli.getSelectedRow(), column);
    }

    public ArrayList<String> getSelectedRows() {
        ArrayList<String> obj = new ArrayList<>();
        for (int i = 0; i < tabMode.getRowCount(); i++) {
            if ((Boolean) tbPoli.getValueAt(i, 0)) {
                obj.add((String) tbPoli.getValueAt(i, 1));
            }
        }
        return obj;
    }

    public long countSelected() {
        int selected = 0;
        for (int i = 0; i < tabMode.getRowCount(); i++) {
            if ((Boolean) tbPoli.getValueAt(i, 0)) {
                selected++;
            }
        }
        return selected;
    }
}
