package khanzahmsanjungan;

import AESsecurity.EnkripsiAES;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import fungsi.koneksiDB;
import fungsi.validasi;
import java.io.File;
import java.io.FileReader;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import java.util.StringJoiner;
import javax.swing.table.DefaultTableModel;

public final class DlgCariPoli extends widget.Dialog {
    private final DefaultTableModel tabMode;
    private final validasi Valid = new validasi();
    private final Connection koneksi = koneksiDB.condb();
    private final Set<String> kodePoliEksekutif = new HashSet<>();
    private String hari = "";

    public DlgCariPoli(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        tabMode = new DefaultTableModel(null, new Object[] {"Kode Unit", "Nama Unit", "registrasi", "registrasilama"}) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 2 || columnIndex == 3) {
                    return Double.class;
                }

                return String.class;
            }
        };
        tbPoli.setModel(tabMode);
        tbPoli.getColumnModel().getColumn(0).setPreferredWidth(100);
        tbPoli.getColumnModel().getColumn(1).setPreferredWidth(700);
        tbPoli.getColumnModel().getColumn(2).setMinWidth(0);
        tbPoli.getColumnModel().getColumn(2).setMaxWidth(0);
        tbPoli.getColumnModel().getColumn(3).setMinWidth(0);
        tbPoli.getColumnModel().getColumn(3).setMaxWidth(0);

        loadPengaturanAPM();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Scroll = new widget.ScrollPane();
        tbPoli = new widget.Table();
        panelBawah = new widget.Panel();
        btnKeluar = new widget.Button();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tbPoli.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbPoli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbPoliMouseReleased(evt);
            }
        });
        Scroll.setViewportView(tbPoli);

        getContentPane().add(Scroll, java.awt.BorderLayout.CENTER);

        panelBawah.setName("panelBawah"); // NOI18N
        panelBawah.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        btnKeluar.setBackground(new java.awt.Color(255, 255, 255));
        btnKeluar.setForeground(new java.awt.Color(255, 23, 26));
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/exit.png"))); // NOI18N
        btnKeluar.setText("KELUAR");
        btnKeluar.setName("btnKeluar"); // NOI18N
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        panelBawah.add(btnKeluar);

        getContentPane().add(panelBawah, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void tbPoliMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPoliMouseReleased
        dispose();
    }//GEN-LAST:event_tbPoliMouseReleased

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Valid.tabelKosongSmc(tabMode);
        StringJoiner sj = new StringJoiner(", ");
        if (!kodePoliEksekutif.isEmpty()) {
            kodePoliEksekutif.iterator().forEachRemaining(s -> sj.add("?"));
        }
        try (PreparedStatement ps = koneksi.prepareStatement(
            "select p.kd_poli, p.nm_poli, p.registrasi, p.registrasilama from poliklinik as p where p.status = '1' " +
            (kodePoliEksekutif.isEmpty() ? "" : "and p.kd_poli in (" + sj.toString() + ") ") +
            "and exists(select * from jadwal as j where j.kd_poli = p.kd_poli and j.hari_kerja = ?) order by p.nm_poli"
        )) {
            int p = 0;
            if (!kodePoliEksekutif.isEmpty()) {
                for (String s : kodePoliEksekutif) {
                    ps.setString(++p, s);
                }
            }
            ps.setString(++p, hari);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    tabMode.addRow(new Object[] {
                        rs.getString("kd_poli"), rs.getString("nm_poli"),
                        rs.getDouble("registrasi"), rs.getDouble("registrasilama")
                    });
                }
            }
        } catch (Exception e) {
            System.out.println("Notif : " + e);
        }
    }//GEN-LAST:event_formWindowActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.ScrollPane Scroll;
    private widget.Button btnKeluar;
    private widget.Panel panelBawah;
    private widget.Table tbPoli;
    // End of variables declaration//GEN-END:variables

    public void setHari(String hari) {
        this.hari = hari;
    }

    public boolean hasSelection() {
        return tbPoli.getSelectedRow() >= 0;
    }

    public Object getSelectedRow(int column) {
        return tbPoli.getValueAt(tbPoli.getSelectedRow(), column);
    }

    private void loadPengaturanAPM() {
        if (new File("./cache/pengaturanapmsmc.iyem").isFile()) {
            try (FileReader fr = new FileReader("./cache/pengaturanapmsmc.iyem")) {
                final ObjectMapper mapper = new ObjectMapper();
                final JsonNode root = mapper.readTree(fr).path("pengaturanapmsmc");
                final JsonNode decrypted = mapper.readTree(EnkripsiAES.decrypt(root.asText()));

                if (decrypted.hasNonNull("kodePoliEksekutif")) {
                    for (JsonNode item : decrypted.withArray("kodePoliEksekutif")) {
                        kodePoliEksekutif.add(item.asText(""));
                    }
                }
            } catch (Exception e) {
                System.out.println("Notif : " + e);
            }
        } else {
            kodePoliEksekutif.clear();
            kodePoliEksekutif.addAll(Arrays.asList(koneksiDB.KODEPOLIEKSEKUTIF()));
        }
    }
}
