package khanzahmsanjungan;

import AESsecurity.EnkripsiAES;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileReader;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.StringJoiner;
import javax.swing.border.TitledBorder;

public class DlgCekDataPasien extends widget.Dialog {
    public static final int REGIST_MANDIRI = 1;
    public static final int CEKIN_BOOKING = 2;

    private static final String TITLE_REGIST_MANDIRI = "::[ Registrasi Mandiri Poliklinik Eksekutif ]::";
    private static final String TITLE_CEKIN_BOOKING = "::[ Cek In Booking Registrasi ]::";

    private final Connection koneksi = koneksiDB.condb();
    private final sekuel Sequel = new sekuel();
    private final validasi Valid = new validasi();
    private final DlgRegistrasiMandiri mandiri;

    private int flag = -1;
    private String printerBarcode = "";
    private int printJumlahBarcode = 0;
    private final Set<String> kodePoliEksekutif = new HashSet<>();

    public DlgCekDataPasien(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.mandiri = new DlgRegistrasiMandiri(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelAtas = new widget.Panel();
        flatLabel1 = new com.formdev.flatlaf.extras.components.FlatLabel();
        panelTengah = new widget.Panel();
        NoRMPasien = new widget.TextField();
        jLabel28 = new widget.Label();
        BtnBatal = new widget.Button();
        BtnKonfirm = new widget.Button();
        panelNumpad1 = new widget.Numpad();
        jLabel1 = new widget.Label();
        jLabel2 = new widget.Label();
        jLabel3 = new widget.Label();
        jLabel4 = new widget.Label();
        jLabel5 = new widget.Label();
        jLabel6 = new widget.Label();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        panelAtas.setMinimumSize(new java.awt.Dimension(500, 100));
        panelAtas.setPreferredSize(new java.awt.Dimension(500, 100));
        panelAtas.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 10));

        flatLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/smc-lg.png"))); // NOI18N
        panelAtas.add(flatLabel1);

        getContentPane().add(panelAtas, java.awt.BorderLayout.PAGE_START);

        panelTengah.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0), "::[ Pendaftaran Eksekutif ]::", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Inter", 0, 24), new java.awt.Color(0, 131, 62))); // NOI18N
        panelTengah.setPreferredSize(new java.awt.Dimension(400, 70));
        panelTengah.setLayout(new java.awt.GridBagLayout());

        NoRMPasien.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 131, 62), 2, true));
        NoRMPasien.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NoRMPasien.setFont(new java.awt.Font("Inter", 0, 36)); // NOI18N
        NoRMPasien.setMinimumSize(new java.awt.Dimension(600, 75));
        NoRMPasien.setMinimumWidth(600);
        NoRMPasien.setPreferredSize(new java.awt.Dimension(600, 75));
        NoRMPasien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NoRMPasienKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelTengah.add(NoRMPasien, gridBagConstraints);

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("No. RM / NIK :");
        jLabel28.setFont(new java.awt.Font("Inter Medium", 0, 36)); // NOI18N
        jLabel28.setMaximumSize(new java.awt.Dimension(32767, 32767));
        jLabel28.setMinimumSize(new java.awt.Dimension(600, 60));
        jLabel28.setPreferredSize(new java.awt.Dimension(600, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(jLabel28, gridBagConstraints);

        BtnBatal.setBackground(new java.awt.Color(255, 255, 255));
        BtnBatal.setForeground(new java.awt.Color(255, 33, 32));
        BtnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/exit.png"))); // NOI18N
        BtnBatal.setMnemonic('U');
        BtnBatal.setText("BATAL");
        BtnBatal.setToolTipText("Alt+U");
        BtnBatal.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        BtnBatal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnBatal.setIconTextGap(2);
        BtnBatal.setMinimumSize(new java.awt.Dimension(200, 75));
        BtnBatal.setMinimumWidth(200);
        BtnBatal.setPreferredSize(new java.awt.Dimension(200, 75));
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        panelTengah.add(BtnBatal, gridBagConstraints);

        BtnKonfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/konfirmasi.png"))); // NOI18N
        BtnKonfirm.setMnemonic('U');
        BtnKonfirm.setText("CEK");
        BtnKonfirm.setToolTipText("Alt+U");
        BtnKonfirm.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        BtnKonfirm.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnKonfirm.setIconTextGap(0);
        BtnKonfirm.setMinimumSize(new java.awt.Dimension(200, 75));
        BtnKonfirm.setMinimumWidth(200);
        BtnKonfirm.setPreferredSize(new java.awt.Dimension(200, 75));
        BtnKonfirm.setVerifyInputWhenFocusTarget(false);
        BtnKonfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKonfirmActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(BtnKonfirm, gridBagConstraints);

        panelNumpad1.setFontSize(36);
        panelNumpad1.setTextBox(NoRMPasien);
        panelNumpad1.setTextLimit(20L);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(panelNumpad1, gridBagConstraints);

        jLabel1.setMaximumSize(new java.awt.Dimension(32767, 32767));
        jLabel1.setMinimumSize(new java.awt.Dimension(200, 75));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(jLabel1, gridBagConstraints);

        jLabel2.setMaximumSize(new java.awt.Dimension(32767, 32767));
        jLabel2.setMinimumSize(new java.awt.Dimension(200, 75));
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(jLabel2, gridBagConstraints);

        jLabel3.setMaximumSize(new java.awt.Dimension(32767, 32767));
        jLabel3.setMinimumSize(new java.awt.Dimension(200, 75));
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(jLabel3, gridBagConstraints);

        jLabel4.setMaximumSize(new java.awt.Dimension(32767, 32767));
        jLabel4.setMinimumSize(new java.awt.Dimension(200, 75));
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(jLabel4, gridBagConstraints);

        jLabel5.setMaximumSize(new java.awt.Dimension(32767, 32767));
        jLabel5.setMinimumSize(new java.awt.Dimension(200, 75));
        jLabel5.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(jLabel5, gridBagConstraints);

        jLabel6.setMaximumSize(new java.awt.Dimension(32767, 32767));
        jLabel6.setMinimumSize(new java.awt.Dimension(200, 75));
        jLabel6.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(jLabel6, gridBagConstraints);

        getContentPane().add(panelTengah, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKonfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKonfirmActionPerformed
        cek();
    }//GEN-LAST:event_BtnKonfirmActionPerformed

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        dispose();
    }//GEN-LAST:event_BtnBatalActionPerformed

    private void NoRMPasienKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NoRMPasienKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cek();
        }
    }//GEN-LAST:event_NoRMPasienKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        loadPengaturanAPM();
        NoRMPasien.setText("");
        NoRMPasien.requestFocus();
    }//GEN-LAST:event_formWindowActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnBatal;
    private widget.Button BtnKonfirm;
    private widget.TextField NoRMPasien;
    private com.formdev.flatlaf.extras.components.FlatLabel flatLabel1;
    private widget.Label jLabel1;
    private widget.Label jLabel2;
    private widget.Label jLabel28;
    private widget.Label jLabel3;
    private widget.Label jLabel4;
    private widget.Label jLabel5;
    private widget.Label jLabel6;
    private widget.Panel panelAtas;
    private widget.Numpad panelNumpad1;
    private widget.Panel panelTengah;
    // End of variables declaration//GEN-END:variables

    public void setFlag(int flag) {
        if (flag <= 0) {
            Valid.popupPeringatanDialog("Flag tidak valid..!!");
            return;
        }

        this.flag = flag;
        TitledBorder border = (TitledBorder) panelTengah.getBorder();

        switch (flag) {
            case REGIST_MANDIRI:
                border.setTitle(TITLE_REGIST_MANDIRI);
                break;
            case CEKIN_BOOKING:
                border.setTitle(TITLE_CEKIN_BOOKING);
                break;
            default:
                border.setTitle(TITLE_REGIST_MANDIRI);
                break;
        }

        repaint();
    }

    private void cek() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        if (NoRMPasien.getText().isBlank()) {
            Valid.popupPeringatanDialog("Isian masih kosong..!!", 3);
        } else {
            String noRM = Sequel.cariIsiSmc("select pasien.no_rkm_medis from pasien where (pasien.no_rkm_medis = ? or trim(pasien.no_ktp) = ?)", NoRMPasien.getText().trim(), NoRMPasien.getText().trim());
            if (noRM.isBlank()) {
                Valid.popupGagalDialog("Data pasien tidak ditemukan..!!", 5);
            } else {
                switch (flag) {
                    case CEKIN_BOOKING:
                        this.cekBooking(noRM);
                        break;
                    case REGIST_MANDIRI:
                        mandiri.setSize(this.getSize());
                        mandiri.setLocationRelativeTo(this);
                        mandiri.setPasien(noRM);
                        mandiri.setVisible(true);
                        this.flag = -1;
                        this.dispose();
                        break;
                }
            }
        }
        formWindowActivated(null);
        this.setCursor(Cursor.getDefaultCursor());
    }

    private void cekBooking(String noRM) {
        StringJoiner sj = new StringJoiner(", ");
        if (!kodePoliEksekutif.isEmpty()) {
            for (int i = 0; i < kodePoliEksekutif.size(); i++) {
                sj.add("?");
            }
        }
        try (PreparedStatement ps = koneksi.prepareStatement(
            "select b.no_rawat, b.status, r.stts, exists(select * from pemeriksaan_ralan as p where p.no_rawat = b.no_rawat) as ada_pemeriksaan from " +
            "booking_registrasi as b join reg_periksa as r on b.no_rawat = r.no_rawat where b.no_rkm_medis = ? and b.tanggal_periksa = current_date() " +
            (sj.length() == 0 ? "" : "and b.kd_poli in (" + sj.toString() + ")")
        )) {
            int p = 0;
            ps.setString(++p, noRM);
            if (!kodePoliEksekutif.isEmpty()) {
                for (String s : kodePoliEksekutif) {
                    ps.setString(++p, s);
                }
            }

            try (ResultSet rs = ps.executeQuery()) {
                if (rs.first()) {
                    Map<String, Object> param = new HashMap<>();
                    param.put("norawat", rs.getString("no_rawat"));
                    param.put("namars", Sequel.cariIsiSmc("select setting.nama_instansi from setting limit 1"));
                    param.put("kotars", Sequel.cariIsiSmc("select setting.kabupaten from setting limit 1"));

                    if (!rs.getString("stts").equals("Belum") || rs.getBoolean("ada_pemeriksaan")) {
                        Valid.popupInfoDialog("Anda sudah menerima pelayanan pada hari ini..!!\nSilahkan konfirmasi ke petugas.");
                    } else if (rs.getString("status").equals("Checkin")) {
                        if (printJumlahBarcode > 0) {
                            if (Valid.popupKonfirmDialog("Anda sudah melakukan checkin pada hari ini\nApakah mau mencetak barcode?") == validasi.POPUP_YA) {
                                Valid.printReportSmc("rptBarcodeRawatAPM.jasper", "report", "::[ Barcode Perawatan ]::", param, printerBarcode, printJumlahBarcode);
                                Valid.popupInfoDialog("Barcode berhasil dicetak..!!", 5);
                            }
                        } else {
                            Valid.popupInfoDialog("Anda sudah melakukan checkin pada hari ini..!!");
                        }
                    } else {
                        Sequel.mengupdateSmc("reg_periksa", "jam_reg = current_time()", "no_rawat = ?", rs.getString("no_rawat"));
                        Sequel.mengupdateSmc("booking_registrasi", "waktu_kunjungan = now(), status = 'Checkin'", "no_rawat = ?", rs.getString("no_rawat"));
                        Valid.popupInfoDialog("Check in berhasil..!!", 5);
                        Valid.printReportSmc("rptBarcodeRawatAPM.jasper", "report", "::[ Barcode Perawatan ]::", param, printerBarcode, printJumlahBarcode);
                    }
                } else {
                    Valid.popupPeringatanDialog("Maaf, jadwal booking untuk hari ini tidak ditemukan\nSilahkan konfirmasi ke pendaftaran..!!");
                }
            }
        } catch (Exception e) {
            System.out.println("Notif : " + e);
            Valid.popupGagalDialog("Terjadi kesalahan pada saat mencari data booking\nSilahkan konfirmasi ke pendaftaran..!!");
        }
    }

    private void loadPengaturanAPM() {
        if (new File("./cache/pengaturanapmsmc.iyem").isFile()) {
            try (FileReader fr = new FileReader("./cache/pengaturanapmsmc.iyem")) {
                final ObjectMapper mapper = new ObjectMapper();
                final JsonNode root = mapper.readTree(fr).path("pengaturanapmsmc");
                final JsonNode decrypted = mapper.readTree(EnkripsiAES.decrypt(root.asText()));

                if (decrypted.hasNonNull("kodePoliEksekutif")) {
                    for (JsonNode item : decrypted.withArray("kodePoliEksekutif")) {
                        kodePoliEksekutif.add(item.asText(""));
                    }
                }

                if (decrypted.hasNonNull("printerBarcode")) {
                    printerBarcode = decrypted.path("printerBarcode").asText();
                }

                if (decrypted.hasNonNull("printJumlahBarcode")) {
                    printJumlahBarcode = decrypted.path("printJumlahBarcode").asInt();
                }
            } catch (Exception e) {
                System.out.println("Notif : " + e);
            }
        } else {
            kodePoliEksekutif.clear();
            kodePoliEksekutif.addAll(Arrays.asList(koneksiDB.KODEPOLIEKSEKUTIF()));
            printerBarcode = koneksiDB.PRINTER_BARCODE();
            printJumlahBarcode = koneksiDB.PRINTJUMLAHBARCODE();
        }
    }
}
