package khanzahmsanjungan;

import AESsecurity.EnkripsiAES;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import fungsi.koneksiDB;
import fungsi.validasi;
import java.io.File;
import java.io.FileReader;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;

public final class DlgCariPoliBPJS extends widget.Dialog {
    private final DefaultTableModel tabMode;
    private final validasi Valid = new validasi();
    private final Connection koneksi = koneksiDB.condb();
    private boolean batasRegistrasiSatuJam = false;
    private String hari = "";
    private String kodeDokter = "";

    public DlgCariPoliBPJS(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        tabMode = new DefaultTableModel(null, new Object[] {"Kode Poli BPJS", "Nama Poli BPJS", "Kode Poli", "Jam Praktek"}) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        tbPoli.setModel(tabMode);
        tbPoli.getColumnModel().getColumn(0).setMinWidth(0);
        tbPoli.getColumnModel().getColumn(0).setMaxWidth(0);
        tbPoli.getColumnModel().getColumn(1).setPreferredWidth(500);
        tbPoli.getColumnModel().getColumn(2).setMinWidth(0);
        tbPoli.getColumnModel().getColumn(2).setMaxWidth(0);
        if (batasRegistrasiSatuJam) {
            tbPoli.getColumnModel().getColumn(3).setPreferredWidth(250);
        } else {
            tbPoli.getColumnModel().getColumn(3).setMinWidth(0);
            tbPoli.getColumnModel().getColumn(3).setMaxWidth(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Scroll = new widget.ScrollPane();
        tbPoli = new widget.Table();
        panelBawah = new widget.Panel();
        btnKeluar = new widget.Button();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Scroll.setName("Scroll"); // NOI18N

        tbPoli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbPoliMouseReleased(evt);
            }
        });
        Scroll.setViewportView(tbPoli);

        getContentPane().add(Scroll, java.awt.BorderLayout.CENTER);

        panelBawah.setName("panelBawah"); // NOI18N
        panelBawah.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        btnKeluar.setBackground(new java.awt.Color(255, 255, 255));
        btnKeluar.setForeground(new java.awt.Color(255, 23, 26));
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/exit.png"))); // NOI18N
        btnKeluar.setText("KELUAR");
        btnKeluar.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        btnKeluar.setName("btnKeluar"); // NOI18N
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        panelBawah.add(btnKeluar);

        getContentPane().add(panelBawah, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        loadPengaturanAPM();
        Valid.tabelKosongSmc(tabMode);
        if (batasRegistrasiSatuJam) {
            try (PreparedStatement ps = koneksi.prepareStatement(
                "select jadwal.kd_poli, concat(left(jadwal.jam_mulai, 5), '-', left(jadwal.jam_selesai, 5)) as jampraktek, " +
                "maping_poli_bpjs.kd_poli_bpjs, maping_poli_bpjs.nm_poli_bpjs from jadwal join maping_poli_bpjs on " +
                "jadwal.kd_poli = maping_poli_bpjs.kd_poli_rs where jadwal.hari_kerja = ? " + (kodeDokter.isBlank() ? ""
                : "and jadwal.kd_dokter = ? ") + "order by jadwal.jam_mulai"
            )) {
                int p = 0;
                ps.setString(++p, hari);
                if (!kodeDokter.isBlank()) {
                    ps.setString(++p, kodeDokter);
                }
                try (ResultSet rs = ps.executeQuery()) {
                    while (rs.next()) {
                        tabMode.addRow(new Object[] {
                            rs.getString("kd_poli_bpjs"), rs.getString("nm_poli_bpjs"), rs.getString("kd_poli"), rs.getString("jampraktek")
                        });
                    }
                }
            } catch (Exception e) {
                System.out.println("Notif : " + e);
            }
        } else {
            try (ResultSet rs = koneksi.createStatement().executeQuery("select * from maping_poli_bpjs")) {
                while (rs.next()) {
                    tabMode.addRow(new String[] {rs.getString("kd_poli_bpjs"), rs.getString("nm_poli_bpjs"), rs.getString("kd_poli_rs"), ""});
                }
            } catch (Exception e) {
                System.out.println("Notif : " + e);
            }
        }
    }//GEN-LAST:event_formWindowActivated

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void tbPoliMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPoliMouseReleased
        dispose();
    }//GEN-LAST:event_tbPoliMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.ScrollPane Scroll;
    private widget.Button btnKeluar;
    private widget.Panel panelBawah;
    private widget.Table tbPoli;
    // End of variables declaration//GEN-END:variables

    public boolean hasSelection() {
        return tbPoli.getSelectedRow() >= 0;
    }

    public Object getSelectedRow(int column) {
        return tbPoli.getValueAt(tbPoli.getSelectedRow(), column);
    }

    public void setHari(String tgl) {
        try {
            Calendar cal = Calendar.getInstance();
            cal.setTime(new SimpleDateFormat("yyyy-MM-dd").parse(tgl));
            switch (cal.get(Calendar.DAY_OF_WEEK)) {
                case 1:
                    hari = "AKHAD";
                    break;
                case 2:
                    hari = "SENIN";
                    break;
                case 3:
                    hari = "SELASA";
                    break;
                case 4:
                    hari = "RABU";
                    break;
                case 5:
                    hari = "KAMIS";
                    break;
                case 6:
                    hari = "JUMAT";
                    break;
                case 7:
                    hari = "SABTU";
                    break;
                default:
                    hari = "";
                    break;
            }
        } catch (Exception e) {
            hari = "";
            System.out.println("Notif : " + e);
        }
    }

    public void setDokter(String kodeDokter) {
        this.kodeDokter = kodeDokter;
    }

    private void loadPengaturanAPM() {
        if (new File("./cache/pengaturanapmsmc.iyem").isFile()) {
            try (FileReader fr = new FileReader("./cache/pengaturanapmsmc.iyem")) {
                final ObjectMapper mapper = new ObjectMapper();
                final JsonNode root = mapper.readTree(fr).path("pengaturanapmsmc");

                batasRegistrasiSatuJam = mapper.readTree(EnkripsiAES.decrypt(root.asText())).path("batasRegistrasiSatuJam").asBoolean();
            } catch (Exception e) {
                System.out.println("Notif : " + e);
            }
        } else {
            batasRegistrasiSatuJam = koneksiDB.REGISTRASISATUJAMSEBELUMJAMPRAKTEK();
        }
    }
}
