package khanzahmsanjungan;

import fungsi.koneksiDB;
import fungsi.validasi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

public final class DlgCariDokter extends widget.Dialog {

    private final DefaultTableModel tabMode;
    private final validasi Valid = new validasi();
    private final Connection koneksi = koneksiDB.condb();

    public DlgCariDokter(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        tabMode = new DefaultTableModel(null, new Object[] {
            "Kode Dokter", "Nama Dokter", "Spesialistik", "Jam Praktek", "Jumlah Pasien"
        }) {
            Class[] type = new Class[] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class,
                java.lang.String.class, java.lang.Integer.class
            };

            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return type[columnIndex];
            }
        };
        tbDokter.setModel(tabMode);

        for (int i = 0; i < 5; i++) {
            TableColumn column = tbDokter.getColumnModel().getColumn(i);
            if (i == 0) {
                column.setMinWidth(0);
                column.setMaxWidth(0);
            } else if (i == 1) {
                column.setPreferredWidth(700);
            } else if (i == 2) {
                column.setPreferredWidth(350);
            } else if (i == 3) {
                column.setPreferredWidth(150);
            } else if (i == 4) {
                column.setPreferredWidth(200);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Scroll = new widget.ScrollPane();
        tbDokter = new widget.Table();
        panelBawah = new widget.Panel();
        btnKeluar = new widget.Button();

        tbDokter.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbDokter.getTableHeader().setResizingAllowed(false);
        tbDokter.getTableHeader().setReorderingAllowed(false);
        tbDokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbDokterMouseReleased(evt);
            }
        });
        Scroll.setViewportView(tbDokter);

        getContentPane().add(Scroll, java.awt.BorderLayout.CENTER);

        panelBawah.setName("panelBawah"); // NOI18N
        panelBawah.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        btnKeluar.setBackground(new java.awt.Color(255, 255, 255));
        btnKeluar.setForeground(new java.awt.Color(255, 23, 26));
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/exit.png"))); // NOI18N
        btnKeluar.setText("KELUAR");
        btnKeluar.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        btnKeluar.setName("btnKeluar"); // NOI18N
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        panelBawah.add(btnKeluar);

        getContentPane().add(panelBawah, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void tbDokterMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDokterMouseReleased
        dispose();
    }//GEN-LAST:event_tbDokterMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.ScrollPane Scroll;
    private widget.Button btnKeluar;
    private widget.Panel panelBawah;
    private widget.Table tbDokter;
    // End of variables declaration//GEN-END:variables

    public void tampil(String harikerja, String kodepoli) {
        Valid.tabelKosongSmc(tabMode);
        try (PreparedStatement ps = koneksi.prepareStatement(
            "select jadwal.kd_dokter, dokter.nm_dokter, spesialis.nm_sps, concat(left(jadwal.jam_mulai, 5), '-', left(jadwal.jam_selesai, 5)), " +
            "(select count(*) from reg_periksa where reg_periksa.kd_dokter = jadwal.kd_dokter and reg_periksa.kd_poli = jadwal.kd_poli and " +
            "reg_periksa.tgl_registrasi = current_date() and reg_periksa.stts != 'Batal') as jumlahdaftar from jadwal join dokter on " +
            "jadwal.kd_dokter = dokter.kd_dokter join spesialis on dokter.kd_sps = spesialis.kd_sps where jadwal.hari_kerja = ? and " +
            "jadwal.kd_poli = ? order by spesialis.nm_sps, jadwal.jam_mulai, dokter.nm_dokter"
        )) {
            ps.setString(1, harikerja);
            ps.setString(2, kodepoli);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    tabMode.addRow(new Object[] {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getInt(5)});
                }
            }
        } catch (Exception e) {
            System.out.println("Notif : " + e);
        }
    }

    public void tampilDokterMapping(String kodeDokterBPJS) {
        Valid.tabelKosongSmc(tabMode);
        try (PreparedStatement ps = koneksi.prepareStatement(
            "select dokter.kd_dokter, dokter.nm_dokter from dokter join maping_dokter_dpjpvclaim on " +
            "dokter.kd_dokter = maping_dokter_dpjpvclaim.kd_dokter where dokter.status = '1' and " +
            "maping_dokter_dpjpvclaim.kd_dokter_bpjs = ?"
        )) {
            ps.setString(1, kodeDokterBPJS);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    tabMode.addRow(new Object[] {rs.getString("kd_dokter"), rs.getString("nm_dokter"), "", "", 0});
                }
            }
        } catch (Exception e) {
            System.out.println("Notif : " + e);
        }
    }

    public boolean hasSelection() {
        return tbDokter.getSelectedRow() >= 0;
    }

    public Object getSelectedRow(int column) {
        return tbDokter.getValueAt(tbDokter.getSelectedRow(), column);
    }
}
