package khanzahmsanjungan;

import fungsi.koneksiDB;
import fungsi.validasi;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

public class DlgLogin extends widget.Dialog {
    private final validasi Valid = new validasi();
    private String akses = "";
    private LoginListener listener = null;

    public DlgLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        InputMap input = getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap action = getRootPane().getActionMap();

        input.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "ESCAPE");
        action.put("ESCAPE", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                userAksi.setText("");
                passAksi.setText("");
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judulAksi = new widget.Label();
        panelTengahAksi = new widget.Panel();
        userAksi = new widget.PasswordField();
        passAksi = new widget.PasswordField();
        label1 = new widget.Label();
        label2 = new widget.Label();
        panelBawahAksi = new widget.Panel();
        btnAksiKonfirmasi = new widget.Button();
        btnAksiBatal = new widget.Button();

        setUndecorated(false);

        judulAksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulAksi.setText("KONFIRMASI AKSI");
        judulAksi.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        judulAksi.setPreferredSize(new java.awt.Dimension(400, 30));
        getContentPane().add(judulAksi, java.awt.BorderLayout.PAGE_START);

        panelTengahAksi.setOpaque(false);
        panelTengahAksi.setLayout(null);

        userAksi.setPreferredSize(new java.awt.Dimension(270, 35));
        userAksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userAksiKeyPressed(evt);
            }
        });
        panelTengahAksi.add(userAksi);
        userAksi.setBounds(120, 30, 270, 35);

        passAksi.setPreferredSize(new java.awt.Dimension(270, 35));
        passAksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passAksiKeyPressed(evt);
            }
        });
        panelTengahAksi.add(passAksi);
        passAksi.setBounds(120, 75, 270, 35);

        label1.setText("User ID :");
        label1.setFocusable(false);
        label1.setPreferredSize(new java.awt.Dimension(60, 35));
        panelTengahAksi.add(label1);
        label1.setBounds(0, 30, 110, 35);

        label2.setText("Password :");
        label2.setFocusable(false);
        label2.setPreferredSize(new java.awt.Dimension(60, 35));
        panelTengahAksi.add(label2);
        label2.setBounds(0, 75, 110, 35);

        getContentPane().add(panelTengahAksi, java.awt.BorderLayout.CENTER);

        panelBawahAksi.setOpaque(false);
        panelBawahAksi.setPreferredSize(new java.awt.Dimension(50, 50));

        btnAksiKonfirmasi.setText("KONFIRMASI");
        btnAksiKonfirmasi.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnAksiKonfirmasi.setPreferredSize(new java.awt.Dimension(140, 35));
        btnAksiKonfirmasi.addActionListener(this::btnAksiKonfirmasiActionPerformed);
        panelBawahAksi.add(btnAksiKonfirmasi);

        btnAksiBatal.setBackground(new java.awt.Color(255, 255, 255));
        btnAksiBatal.setForeground(new java.awt.Color(255, 23, 26));
        btnAksiBatal.setText("Batal");
        btnAksiBatal.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        btnAksiBatal.setPreferredSize(new java.awt.Dimension(90, 35));
        btnAksiBatal.addActionListener(this::btnAksiBatalActionPerformed);
        panelBawahAksi.add(btnAksiBatal);

        getContentPane().add(panelBawahAksi, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userAksiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userAksiKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnAksiKonfirmasiActionPerformed(null);
        }
    }//GEN-LAST:event_userAksiKeyPressed

    private void passAksiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passAksiKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnAksiKonfirmasiActionPerformed(null);
        } else if (evt.getKeyCode() == KeyEvent.VK_PAGE_UP) {
            userAksi.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_PAGE_DOWN) {
            btnAksiKonfirmasi.requestFocus();
        }
    }//GEN-LAST:event_passAksiKeyPressed

    private void btnAksiKonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAksiKonfirmasiActionPerformed
        try (PreparedStatement ps = koneksiDB.condb().prepareStatement(
            "select 1 as admine, null as kasir_ralan, null as bpjs_sep from admin where admin.usere = aes_encrypt(?, 'nur') and admin.passworde = aes_encrypt(?, 'windi') union all " +
            "select 0 as admine, user.kasir_ralan, user.bpjs_sep from user where user.id_user = aes_encrypt(?, 'nur') and user.password = aes_encrypt(?, 'windi')"
        )) {
            String user = new String(userAksi.getPassword());
            String pass = new String(passAksi.getPassword());
            ps.setString(1, user);
            ps.setString(2, pass);
            ps.setString(3, user);
            ps.setString(4, pass);
            try (ResultSet rs = ps.executeQuery()) {
                userAksi.setText("");
                passAksi.setText("");
                if (rs.next()) {
                    if (rs.getBoolean("admine")) {
                        dispose();
                        LoggedInEvent event = new LoggedInEvent(true, null, "Admin Utama");
                        if (listener != null) {
                            listener.onLogin(event);
                        }
                    } else if (rs.getString(akses).equals("true")) {
                        dispose();
                        LoggedInEvent event = new LoggedInEvent(false, akses, user);
                        if (listener != null) {
                            listener.onLogin(event);
                        }
                    } else {
                        userAksi.requestFocus();
                        Valid.popupGagalDialog("Terjadi kesalahan..!!", 3);
                    }
                } else {
                    userAksi.requestFocus();
                    Valid.popupGagalDialog("Terjadi kesalahan..!!", 3);
                }
                user = pass = null;
            }
        } catch (Exception e) {
            System.out.println("Notif : " + e);
            userAksi.setText("");
            passAksi.setText("");
            userAksi.requestFocus();
            Valid.popupGagalDialog("Terjadi kesalahan..!!", 3);
        }
    }//GEN-LAST:event_btnAksiKonfirmasiActionPerformed

    private void btnAksiBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAksiBatalActionPerformed
        userAksi.setText("");
        passAksi.setText("");
        dispose();
    }//GEN-LAST:event_btnAksiBatalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button btnAksiBatal;
    private widget.Button btnAksiKonfirmasi;
    private widget.Label judulAksi;
    private widget.Label label1;
    private widget.Label label2;
    private widget.Panel panelBawahAksi;
    private widget.Panel panelTengahAksi;
    private widget.PasswordField passAksi;
    private widget.PasswordField userAksi;
    // End of variables declaration//GEN-END:variables

    public void setOnLoginListener(LoginListener listener) {
        this.listener = listener;
    }

    public void requireAkses(final String akses) {
        this.akses = akses;
    }

    public static class LoggedInEvent {
        private final boolean admin;
        private final String akses;
        private final String userID;

        public LoggedInEvent(final boolean admin, final String akses, final String userID) {
            this.admin = admin;
            this.akses = akses;
            this.userID = userID;
        }

        public String getUserID() {
            return this.userID;
        }

        public boolean isAdmin() {
            return this.admin;
        }

        public boolean punyaAkses(String namaAkses) {
            if (this.isAdmin()) {
                return true;
            }

            return akses.equals(namaAkses);
        }
    }

    @FunctionalInterface
    public static interface LoginListener {
        public void onLogin(LoggedInEvent event);
    }
}
