package khanzahmsanjungan;

import AESsecurity.EnkripsiAES;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import fungsi.BatasInput;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.StreamSupport;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

public class DlgPengaturanAPM extends widget.Dialog {
    private final validasi Valid = new validasi();
    private DlgCariPoli2 poli = null;
    private String userLoginFP = "", passLoginFP = "";
    private List<String> listPoli = null;

    /**
     * Creates new form DlgPengaturanAPM
     */
    public DlgPengaturanAPM(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jumlahBarcode.setDocument(new BatasInput().hanyaInteger(2));
        jumlahAntrianFarmasi.setDocument(new BatasInput().hanyaInteger(2));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        fc = new javax.swing.JFileChooser();
        panel1 = new widget.Panel();
        printerRegist = new widget.ComboBox();
        printerBarcode = new widget.ComboBox();
        printerAntrian = new widget.ComboBox();
        jumlahBarcode = new widget.TextField();
        userFP = new widget.PasswordField();
        passFP = new widget.PasswordField();
        enableAntrian = new widget.CekBox();
        enableAntrianFarmasi = new widget.CekBox();
        enableCekin = new widget.CekBox();
        enableDaftarPoli = new widget.CekBox();
        enableSEPPertama = new widget.CekBox();
        enableSEPKontrol = new widget.CekBox();
        enableSEPBedaPoli = new widget.CekBox();
        enableMobileJKN = new widget.CekBox();
        enableSatuSehat = new widget.CekBox();
        pilihPoliEksekutif = new widget.Button();
        label1 = new widget.Label();
        label2 = new widget.Label();
        label3 = new widget.Label();
        label5 = new widget.Label();
        label6 = new widget.Label();
        label7 = new widget.Label();
        label8 = new widget.Label();
        label9 = new widget.Label();
        label10 = new widget.Label();
        label11 = new widget.Label();
        pathFingerprint = new widget.TextField();
        pathFrista = new widget.TextField();
        cariLokasiFingerprint = new widget.Button();
        cariLokasiFrista = new widget.Button();
        label13 = new widget.Label();
        jumlahAntrianFarmasi = new widget.TextField();
        enableVBFrista = new widget.CekBox();
        enableVBFingerprint = new widget.CekBox();
        label12 = new widget.Label();
        batasRegistrasiSatuJam = new widget.CekBox();
        peekUserFP = new widget.Button();
        peekPasswordFP = new widget.Button();
        labelPoliAktif = new widget.Label();
        panel2 = new widget.Panel();
        btnSimpan = new widget.Button();
        btnBatal = new widget.Button();

        setTitle("Pengaturan APM");
        setBounds(new java.awt.Rectangle(0, 0, 960, 540));
        setMinimumSize(new java.awt.Dimension(960, 540));
        setUndecorated(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panel1.setForeground(new java.awt.Color(100, 131, 100));
        panel1.setLayout(null);

        printerRegist.setPreferredSize(new java.awt.Dimension(400, 35));
        printerRegist.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                printerRegistKeyPressed(evt);
            }
        });
        panel1.add(printerRegist);
        printerRegist.setBounds(247, 10, 400, 35);

        printerBarcode.setPreferredSize(new java.awt.Dimension(400, 35));
        printerBarcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                printerBarcodeKeyPressed(evt);
            }
        });
        panel1.add(printerBarcode);
        printerBarcode.setBounds(247, 50, 400, 35);

        printerAntrian.setPreferredSize(new java.awt.Dimension(400, 35));
        printerAntrian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                printerAntrianKeyPressed(evt);
            }
        });
        panel1.add(printerAntrian);
        printerAntrian.setBounds(247, 90, 400, 35);

        jumlahBarcode.setMinimumSize(new java.awt.Dimension(75, 35));
        jumlahBarcode.setPreferredSize(new java.awt.Dimension(75, 35));
        panel1.add(jumlahBarcode);
        jumlahBarcode.setBounds(732, 50, 75, 35);

        userFP.setText("passwordField1");
        userFP.setPreferredSize(new java.awt.Dimension(300, 35));
        panel1.add(userFP);
        userFP.setBounds(247, 250, 300, 35);

        passFP.setText("passwordField2");
        passFP.setPreferredSize(new java.awt.Dimension(300, 35));
        panel1.add(passFP);
        passFP.setBounds(247, 290, 300, 35);

        enableAntrian.setForeground(new java.awt.Color(0, 131, 62));
        enableAntrian.setText("Antrian Loket");
        enableAntrian.setPreferredSize(new java.awt.Dimension(140, 30));
        enableAntrian.setStyle("");
        enableAntrian.setStyleClass("");
        panel1.add(enableAntrian);
        enableAntrian.setBounds(247, 334, 140, 30);

        enableAntrianFarmasi.setForeground(new java.awt.Color(0, 131, 62));
        enableAntrianFarmasi.setText("Antrian Farmasi");
        enableAntrianFarmasi.setPreferredSize(new java.awt.Dimension(140, 30));
        enableAntrianFarmasi.setStyle("");
        enableAntrianFarmasi.setStyleClass("");
        panel1.add(enableAntrianFarmasi);
        enableAntrianFarmasi.setBounds(247, 364, 140, 30);

        enableCekin.setForeground(new java.awt.Color(0, 131, 62));
        enableCekin.setText("Cek In Booking");
        enableCekin.setPreferredSize(new java.awt.Dimension(140, 30));
        enableCekin.setStyle("");
        enableCekin.setStyleClass("");
        panel1.add(enableCekin);
        enableCekin.setBounds(247, 394, 140, 30);

        enableDaftarPoli.setForeground(new java.awt.Color(0, 131, 62));
        enableDaftarPoli.setText("Pendaftaran Poliklinik");
        enableDaftarPoli.setPreferredSize(new java.awt.Dimension(200, 30));
        enableDaftarPoli.setStyle("");
        enableDaftarPoli.setStyleClass("");
        panel1.add(enableDaftarPoli);
        enableDaftarPoli.setBounds(387, 334, 200, 30);

        enableSEPPertama.setForeground(new java.awt.Color(0, 131, 62));
        enableSEPPertama.setText("SEP Kunjungan Pertama");
        enableSEPPertama.setPreferredSize(new java.awt.Dimension(200, 30));
        enableSEPPertama.setStyle("");
        enableSEPPertama.setStyleClass("");
        panel1.add(enableSEPPertama);
        enableSEPPertama.setBounds(387, 364, 200, 30);

        enableSEPKontrol.setForeground(new java.awt.Color(0, 131, 62));
        enableSEPKontrol.setText("SEP Kontrol");
        enableSEPKontrol.setPreferredSize(new java.awt.Dimension(200, 30));
        enableSEPKontrol.setStyle("");
        enableSEPKontrol.setStyleClass("");
        panel1.add(enableSEPKontrol);
        enableSEPKontrol.setBounds(387, 394, 200, 30);

        enableSEPBedaPoli.setForeground(new java.awt.Color(0, 131, 62));
        enableSEPBedaPoli.setText("SEP Kontrol Beda Poli");
        enableSEPBedaPoli.setPreferredSize(new java.awt.Dimension(170, 30));
        enableSEPBedaPoli.setStyle("");
        enableSEPBedaPoli.setStyleClass("");
        panel1.add(enableSEPBedaPoli);
        enableSEPBedaPoli.setBounds(587, 334, 170, 30);

        enableMobileJKN.setForeground(new java.awt.Color(0, 131, 62));
        enableMobileJKN.setText("Cek In MobileJKN");
        enableMobileJKN.setPreferredSize(new java.awt.Dimension(170, 30));
        enableMobileJKN.setStyle("");
        enableMobileJKN.setStyleClass("");
        panel1.add(enableMobileJKN);
        enableMobileJKN.setBounds(587, 364, 170, 30);

        enableSatuSehat.setForeground(new java.awt.Color(0, 131, 62));
        enableSatuSehat.setText("Aktivasi Satu Sehat");
        enableSatuSehat.setPreferredSize(new java.awt.Dimension(170, 30));
        enableSatuSehat.setStyle("");
        enableSatuSehat.setStyleClass("");
        panel1.add(enableSatuSehat);
        enableSatuSehat.setBounds(587, 394, 170, 30);

        pilihPoliEksekutif.setBackground(new java.awt.Color(240, 249, 255));
        pilihPoliEksekutif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/pilih.png"))); // NOI18N
        pilihPoliEksekutif.setPreferredSize(new java.awt.Dimension(45, 35));
        pilihPoliEksekutif.addActionListener(this::pilihPoliEksekutifActionPerformed);
        panel1.add(pilihPoliEksekutif);
        pilihPoliEksekutif.setBounds(247, 130, 45, 35);

        label1.setText("Printer Registrasi/SEP :");
        panel1.add(label1);
        label1.setBounds(0, 10, 240, 35);

        label2.setText("Printer Barcode :");
        panel1.add(label2);
        label2.setBounds(0, 50, 240, 35);

        label3.setText("Printer Antrian :");
        panel1.add(label3);
        label3.setBounds(0, 90, 240, 35);

        label5.setText("Path Aplikasi Fingerprint :");
        panel1.add(label5);
        label5.setBounds(0, 170, 240, 35);

        label6.setText("Path Aplikasi FRISTA :");
        panel1.add(label6);
        label6.setBounds(0, 210, 240, 35);

        label7.setText("Username FP / FRISTA :");
        panel1.add(label7);
        label7.setBounds(0, 250, 240, 35);

        label8.setText("Password FP / FRISTA :");
        panel1.add(label8);
        label8.setBounds(0, 290, 240, 35);

        label9.setText("Menu diaktifkan :");
        panel1.add(label9);
        label9.setBounds(0, 330, 240, 35);

        label10.setText("Poli Eksekutif :");
        panel1.add(label10);
        label10.setBounds(0, 130, 240, 35);

        label11.setText("Jumlah :");
        panel1.add(label11);
        label11.setBounds(652, 50, 73, 35);

        pathFingerprint.setEditable(false);
        pathFingerprint.setPreferredSize(new java.awt.Dimension(400, 35));
        pathFingerprint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pathFingerprintKeyPressed(evt);
            }
        });
        panel1.add(pathFingerprint);
        pathFingerprint.setBounds(247, 170, 400, 35);

        pathFrista.setEditable(false);
        pathFrista.setPreferredSize(new java.awt.Dimension(400, 35));
        pathFrista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pathFristaKeyPressed(evt);
            }
        });
        panel1.add(pathFrista);
        pathFrista.setBounds(247, 210, 400, 35);

        cariLokasiFingerprint.setBackground(new java.awt.Color(240, 249, 255));
        cariLokasiFingerprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/pilih.png"))); // NOI18N
        cariLokasiFingerprint.setPreferredSize(new java.awt.Dimension(45, 35));
        cariLokasiFingerprint.addActionListener(this::cariLokasiFingerprintActionPerformed);
        panel1.add(cariLokasiFingerprint);
        cariLokasiFingerprint.setBounds(652, 170, 45, 35);

        cariLokasiFrista.setBackground(new java.awt.Color(240, 249, 255));
        cariLokasiFrista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/pilih.png"))); // NOI18N
        cariLokasiFrista.setPreferredSize(new java.awt.Dimension(45, 35));
        cariLokasiFrista.addActionListener(this::cariLokasiFristaActionPerformed);
        panel1.add(cariLokasiFrista);
        cariLokasiFrista.setBounds(652, 210, 45, 35);

        label13.setText("Jumlah untuk Farmasi :");
        panel1.add(label13);
        label13.setBounds(652, 90, 201, 35);

        jumlahAntrianFarmasi.setMinimumSize(new java.awt.Dimension(75, 35));
        jumlahAntrianFarmasi.setPreferredSize(new java.awt.Dimension(75, 35));
        panel1.add(jumlahAntrianFarmasi);
        jumlahAntrianFarmasi.setBounds(858, 90, 75, 35);

        enableVBFrista.setForeground(new java.awt.Color(0, 131, 62));
        enableVBFrista.setText("Aktifkan");
        enableVBFrista.setFont(new java.awt.Font("Inter Medium", 0, 18)); // NOI18N
        enableVBFrista.setPreferredSize(new java.awt.Dimension(130, 30));
        enableVBFrista.setStyle("");
        enableVBFrista.setStyleClass("");
        panel1.add(enableVBFrista);
        enableVBFrista.setBounds(702, 215, 130, 30);

        enableVBFingerprint.setForeground(new java.awt.Color(0, 131, 62));
        enableVBFingerprint.setText("Aktifkan");
        enableVBFingerprint.setFont(new java.awt.Font("Inter Medium", 0, 18)); // NOI18N
        enableVBFingerprint.setPreferredSize(new java.awt.Dimension(130, 30));
        enableVBFingerprint.setStyle("");
        enableVBFingerprint.setStyleClass("");
        panel1.add(enableVBFingerprint);
        enableVBFingerprint.setBounds(702, 175, 130, 30);

        label12.setText("Khusus Admin :");
        panel1.add(label12);
        label12.setBounds(0, 430, 240, 35);

        batasRegistrasiSatuJam.setForeground(new java.awt.Color(0, 131, 62));
        batasRegistrasiSatuJam.setText("Batas Registrasi / Cek In 1 Jam Sebelum Jadwal Praktek");
        batasRegistrasiSatuJam.setToolTipText("Hanya boleh dilakukan oleh admin");
        batasRegistrasiSatuJam.setEnabled(false);
        batasRegistrasiSatuJam.setPreferredSize(new java.awt.Dimension(410, 30));
        batasRegistrasiSatuJam.setStyle("");
        batasRegistrasiSatuJam.setStyleClass("");
        panel1.add(batasRegistrasiSatuJam);
        batasRegistrasiSatuJam.setBounds(247, 434, 410, 30);

        peekUserFP.setBackground(new java.awt.Color(240, 249, 255));
        peekUserFP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/eye2.png"))); // NOI18N
        peekUserFP.setPreferredSize(new java.awt.Dimension(45, 35));
        peekUserFP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                peekUserFPMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                peekUserFPMouseReleased(evt);
            }
        });
        panel1.add(peekUserFP);
        peekUserFP.setBounds(552, 250, 45, 35);

        peekPasswordFP.setBackground(new java.awt.Color(240, 249, 255));
        peekPasswordFP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/eye2.png"))); // NOI18N
        peekPasswordFP.setPreferredSize(new java.awt.Dimension(45, 35));
        peekPasswordFP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                peekPasswordFPMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                peekPasswordFPMouseReleased(evt);
            }
        });
        panel1.add(peekPasswordFP);
        peekPasswordFP.setBounds(552, 290, 45, 35);

        labelPoliAktif.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelPoliAktif.setText("3 Poli Aktif");
        labelPoliAktif.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        labelPoliAktif.setPreferredSize(new java.awt.Dimension(348, 30));
        panel1.add(labelPoliAktif);
        labelPoliAktif.setBounds(299, 135, 348, 30);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(panel1, gridBagConstraints);

        panel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        btnSimpan.setText("SIMPAN");
        btnSimpan.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnSimpan.setPreferredSize(new java.awt.Dimension(150, 35));
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);
        panel2.add(btnSimpan);

        btnBatal.setBackground(new java.awt.Color(240, 249, 255));
        btnBatal.setForeground(new java.awt.Color(100, 131, 100));
        btnBatal.setText("BATAL");
        btnBatal.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnBatal.setPreferredSize(new java.awt.Dimension(150, 35));
        btnBatal.addActionListener(this::btnBatalActionPerformed);
        panel2.add(btnBatal);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(panel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printerRegistKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_printerRegistKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == KeyEvent.VK_DELETE) {
            evt.consume();
            printerRegist.setSelectedItem("");
        }
    }//GEN-LAST:event_printerRegistKeyPressed

    private void printerBarcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_printerBarcodeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == KeyEvent.VK_DELETE) {
            evt.consume();
            printerBarcode.setSelectedItem("");
        }
    }//GEN-LAST:event_printerBarcodeKeyPressed

    private void printerAntrianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_printerAntrianKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == KeyEvent.VK_DELETE) {
            evt.consume();
            printerAntrian.setSelectedItem("");
        }
    }//GEN-LAST:event_printerAntrianKeyPressed

    private void pilihPoliEksekutifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihPoliEksekutifActionPerformed
        if (poli == null) {
            poli = new DlgCariPoli2(null, false);
            poli.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    if (poli.hasSelection()) {
                        listPoli = poli.getSelectedRows();
                    }
                    labelPoliAktif.setText(listPoli.size() + " Poli Aktif");
                }
            });
        }
        poli.tampil();
        poli.setSelectedRows(listPoli);
        poli.setSize(getContentPane().getSize());
        poli.setLocationRelativeTo(getContentPane());
        poli.setVisible(true);
    }//GEN-LAST:event_pilihPoliEksekutifActionPerformed

    private void pathFingerprintKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pathFingerprintKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == KeyEvent.VK_DELETE) {
            evt.consume();
            if (pathFingerprint.getText().length() > 0) {
                pathFingerprint.setText("");
            }
        }
    }//GEN-LAST:event_pathFingerprintKeyPressed

    private void pathFristaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pathFristaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == KeyEvent.VK_DELETE) {
            evt.consume();
            if (pathFrista.getText().length() > 0) {
                pathFrista.setText("");
            }
        }
    }//GEN-LAST:event_pathFristaKeyPressed

    private void cariLokasiFingerprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariLokasiFingerprintActionPerformed
        if (!pathFingerprint.getText().isBlank()) {
            fc.setCurrentDirectory(new File(pathFingerprint.getText().substring(0, pathFingerprint.getText().lastIndexOf(File.separator))));
        }

        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            pathFingerprint.setText(fc.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_cariLokasiFingerprintActionPerformed

    private void cariLokasiFristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariLokasiFristaActionPerformed
        if (!pathFrista.getText().isBlank()) {
            fc.setCurrentDirectory(new File(pathFrista.getText().substring(0, pathFrista.getText().lastIndexOf(File.separator))));
        }

        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            pathFrista.setText(fc.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_cariLokasiFristaActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if (simpan()) {
            dispose();
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void peekUserFPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peekUserFPMousePressed
        peekUserFP.setIcon(new ImageIcon(getClass().getResource("/48x48/eye.png")));
        if (new String(userFP.getPassword()).equals("************")) {
            userFP.setText(EnkripsiAES.decrypt(userLoginFP));
        }
        userFP.setEchoChar((char) 0);
    }//GEN-LAST:event_peekUserFPMousePressed

    private void peekUserFPMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peekUserFPMouseReleased
        peekUserFP.setIcon(new ImageIcon(getClass().getResource("/48x48/eye2.png")));
        if (new String(userFP.getPassword()).equals(EnkripsiAES.decrypt(userLoginFP))) {
            userFP.setText("************");
        }
        userFP.setEchoChar('\u2022');
    }//GEN-LAST:event_peekUserFPMouseReleased

    private void peekPasswordFPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peekPasswordFPMousePressed
        peekPasswordFP.setIcon(new ImageIcon(getClass().getResource("/48x48/eye.png")));
        if (new String(passFP.getPassword()).equals("************")) {
            passFP.setText(EnkripsiAES.decrypt(passLoginFP));
        }
        passFP.setEchoChar((char) 0);
    }//GEN-LAST:event_peekPasswordFPMousePressed

    private void peekPasswordFPMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peekPasswordFPMouseReleased
        peekPasswordFP.setIcon(new ImageIcon(getClass().getResource("/48x48/eye2.png")));
        if (new String(passFP.getPassword()).equals(EnkripsiAES.decrypt(passLoginFP))) {
            passFP.setText("************");
        }
        passFP.setEchoChar('\u2022');
    }//GEN-LAST:event_peekPasswordFPMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.CekBox batasRegistrasiSatuJam;
    private widget.Button btnBatal;
    private widget.Button btnSimpan;
    private widget.Button cariLokasiFingerprint;
    private widget.Button cariLokasiFrista;
    private widget.CekBox enableAntrian;
    private widget.CekBox enableAntrianFarmasi;
    private widget.CekBox enableCekin;
    private widget.CekBox enableDaftarPoli;
    private widget.CekBox enableMobileJKN;
    private widget.CekBox enableSEPBedaPoli;
    private widget.CekBox enableSEPKontrol;
    private widget.CekBox enableSEPPertama;
    private widget.CekBox enableSatuSehat;
    private widget.CekBox enableVBFingerprint;
    private widget.CekBox enableVBFrista;
    private javax.swing.JFileChooser fc;
    private widget.TextField jumlahAntrianFarmasi;
    private widget.TextField jumlahBarcode;
    private widget.Label label1;
    private widget.Label label10;
    private widget.Label label11;
    private widget.Label label12;
    private widget.Label label13;
    private widget.Label label2;
    private widget.Label label3;
    private widget.Label label5;
    private widget.Label label6;
    private widget.Label label7;
    private widget.Label label8;
    private widget.Label label9;
    private widget.Label labelPoliAktif;
    private widget.Panel panel1;
    private widget.Panel panel2;
    private widget.PasswordField passFP;
    private widget.TextField pathFingerprint;
    private widget.TextField pathFrista;
    private widget.Button peekPasswordFP;
    private widget.Button peekUserFP;
    private widget.Button pilihPoliEksekutif;
    private widget.ComboBox printerAntrian;
    private widget.ComboBox printerBarcode;
    private widget.ComboBox printerRegist;
    private widget.PasswordField userFP;
    // End of variables declaration//GEN-END:variables

    public void tampil(final boolean admin) {
        printerRegist.removeAllItems();
        printerBarcode.removeAllItems();
        printerAntrian.removeAllItems();

        printerRegist.addItem("");
        printerBarcode.addItem("");
        printerAntrian.addItem("");

        for (PrintService ps : PrintServiceLookup.lookupPrintServices(null, null)) {
            printerRegist.addItem(ps.getName());
            printerBarcode.addItem(ps.getName());
            printerAntrian.addItem(ps.getName());
        }

        if (new File("./cache/pengaturanapmsmc.iyem").isFile()) {
            final ObjectMapper mapper = new ObjectMapper();
            try (FileReader fr = new FileReader("./cache/pengaturanapmsmc.iyem")) {
                final JsonNode root = mapper.readTree(fr).path("pengaturanapmsmc");
                final JsonNode decrypted = mapper.readTree(EnkripsiAES.decrypt(root.asText()));

                printerRegist.setSelectedItem(decrypted.path("printerRegist").asText(""));
                printerBarcode.setSelectedItem(decrypted.path("printerBarcode").asText(""));
                printerAntrian.setSelectedItem(decrypted.path("printerAntrian").asText(""));
                jumlahBarcode.setText(decrypted.path("printJumlahBarcode").asText(""));
                jumlahAntrianFarmasi.setText(decrypted.path("printJumlahAntrianFarmasi").asText(""));

                listPoli = StreamSupport.stream(decrypted.withArray("kodePoliEksekutif").spliterator(), false)
                    .map(JsonNode::asText)
                    .collect(Collectors.toCollection(ArrayList::new));

                labelPoliAktif.setText(listPoli.size() + " Poli Aktif");

                pathFingerprint.setText(decrypted.path("fingerprint").path("path").asText(""));
                enableVBFingerprint.setSelected(decrypted.path("fingerprint").path("aktifkan").asBoolean(false));
                pathFrista.setText(decrypted.path("frista").path("path").asText(""));
                enableVBFrista.setSelected(decrypted.path("frista").path("aktifkan").asBoolean(true));

                userLoginFP = decrypted.path("userFP").asText(EnkripsiAES.encrypt(""));
                passLoginFP = decrypted.path("passFP").asText(EnkripsiAES.encrypt(""));
                userFP.setText("************");
                passFP.setText("************");

                Collection<String> c = StreamSupport.stream(decrypted.path("tombolDiaktifkan").spliterator(), false).map(JsonNode::asText).collect(Collectors.toList());
                enableAntrian.setSelected(c.contains("antrian"));
                enableAntrianFarmasi.setSelected(c.contains("antrianfarmasi"));
                enableCekin.setSelected(c.contains("cekin"));
                enableDaftarPoli.setSelected(c.contains("daftarpoli"));
                enableSEPPertama.setSelected(c.contains("seppertama"));
                enableSEPKontrol.setSelected(c.contains("sepkontrol"));
                enableSEPBedaPoli.setSelected(c.contains("sepbedapoli"));
                enableMobileJKN.setSelected(c.contains("mobilejkn"));
                enableSatuSehat.setSelected(c.contains("satusehat"));

                batasRegistrasiSatuJam.setEnabled(admin);
                batasRegistrasiSatuJam.setSelected(decrypted.path("batasRegistrasiSatuJam").asBoolean(false));
            } catch (Exception e) {
                System.out.println("Notif : " + e);
            }
        }
    }

    private boolean simpan() {
        try {
            File iyem = new File("./cache/pengaturanapmsmc.iyem");
            iyem.createNewFile();

            try (FileWriter fw = new FileWriter(iyem)) {
                final ObjectMapper mapper = new ObjectMapper();
                final ObjectNode root = mapper.createObjectNode();

                root.put("printerRegist", printerRegist.getSelectedItem().toString());
                root.put("printerBarcode", printerBarcode.getSelectedItem().toString());
                root.put("printerAntrian", printerAntrian.getSelectedItem().toString());

                if (!jumlahBarcode.getText().isBlank()) {
                    root.put("printJumlahBarcode", Integer.parseInt(jumlahBarcode.getText()));
                } else {
                    root.put("printJumlahBarcode", 0);
                }

                if (!jumlahAntrianFarmasi.getText().isBlank()) {
                    root.put("printJumlahAntrianFarmasi", Integer.parseInt(jumlahAntrianFarmasi.getText()));
                } else {
                    root.put("printJumlahAntrianFarmasi", 0);
                }

                root.withObject("fingerprint").put("path", pathFingerprint.getText());
                root.withObject("fingerprint").put("aktifkan", enableVBFingerprint.isSelected());
                root.withObject("frista").put("path", pathFrista.getText());
                root.withObject("frista").put("aktifkan", enableVBFrista.isSelected());

                root.set("kodePoliEksekutif", mapper.valueToTree(listPoli));

                String user = new String(userFP.getPassword());
                String pass = new String(passFP.getPassword());

                if ("************".equals(user) && "************".equals(pass)) {
                    root.put("userFP", userLoginFP);
                    root.put("passFP", passLoginFP);
                } else {
                    root.put("userFP", EnkripsiAES.encrypt(user));
                    root.put("passFP", EnkripsiAES.encrypt(pass));
                }

                final ArrayNode td = mapper.createArrayNode();
                if (enableAntrian.isSelected()) {
                    td.add("antrian");
                }
                if (enableAntrianFarmasi.isSelected()) {
                    td.add("antrianfarmasi");
                }
                if (enableCekin.isSelected()) {
                    td.add("cekin");
                }
                if (enableDaftarPoli.isSelected()) {
                    td.add("daftarpoli");
                }
                if (enableSEPPertama.isSelected()) {
                    td.add("seppertama");
                }
                if (enableSEPKontrol.isSelected()) {
                    td.add("sepkontrol");
                }
                if (enableSEPBedaPoli.isSelected()) {
                    td.add("sepbedapoli");
                }
                if (enableMobileJKN.isSelected()) {
                    td.add("mobilejkn");
                }
                if (enableSatuSehat.isSelected()) {
                    td.add("satusehat");
                }
                root.set("tombolDiaktifkan", td);

                root.put("batasRegistrasiSatuJam", batasRegistrasiSatuJam.isSelected());

                String encrypted = EnkripsiAES.encrypt(mapper.writeValueAsString(root));
                fw.write(mapper.writeValueAsString(mapper.createObjectNode().put("pengaturanapmsmc", encrypted)));
                fw.flush();
            }
            Valid.popupInfoDialog("Pengaturan berhasil disimpan..!!", 3);
            return true;
        } catch (Exception e) {
            System.out.println("Notif : " + e);
            Valid.popupGagalDialog("Gagal menyimpan pengaturan: " + e.getMessage(), 3);
            return false;
        }
    }
}
