package khanzahmsanjungan;

import AESsecurity.EnkripsiAES;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.Cursor;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileReader;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.stream.StreamSupport;

public class DlgRegistrasiMandiri extends widget.Dialog {

    private final Connection koneksi = koneksiDB.condb();
    private final sekuel Sequel = new sekuel();
    private final validasi Valid = new validasi();
    private final DlgCariPoli poli;
    private final DlgCariDokter dokter;
    private final String URUTNOREG = koneksiDB.URUTNOREG();
    private int printJumlahBarcode = 0;
    private String hari = "",
        noRawat = "",
        noReg = "",
        kdDokter = "",
        kdPoli = "",
        biayaReg = "",
        statusDaftar = "Lama",
        statusPoli = "Baru",
        umurDaftar = "0",
        statusUmur = "Th",
        namaPJ = "-",
        hubunganPJ = "-",
        alamatPJ = "-",
        instansiNama = "",
        instansiAlamat = "",
        instansiKota = "",
        instansiKontak = "",
        poliBiaya = "",
        poliBiayaLama = "",
        umurPasien = "",
        printerBarcode = "",
        kodePoliEksekutif = "";

    public DlgRegistrasiMandiri(java.awt.Frame parent, boolean model) {
        super(parent, model);
        dokter = new DlgCariDokter(parent, model);
        poli = new DlgCariPoli(parent, model);
        initComponents();
        loadPengaturanAPM();

        try (ResultSet rs = koneksi.prepareStatement("select nama_instansi, alamat_instansi, kabupaten, kontak from setting").executeQuery()) {
            if (rs.next()) {
                instansiNama = rs.getString("nama_instansi");
                instansiAlamat = rs.getString("alamat_instansi");
                instansiKota = rs.getString("kabupaten");
                instansiKontak = rs.getString("kontak");
            }
        } catch (SQLException e) {
            System.out.println("Notif : " + e);
        }

        dokter.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                if (dokter.hasSelection()) {
                    kdDokter = dokter.getSelectedRow(0).toString();
                    namaDokter.setText(dokter.getSelectedRow(1).toString());
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelAtas = new widget.Panel();
        label1 = new widget.Label();
        emptyKiri = new widget.Panel();
        panelTengah = new widget.Panel();
        jLabel10 = new widget.Label();
        jLabel29 = new widget.Label();
        jLabel31 = new widget.Label();
        noRM = new widget.Label();
        jLabel32 = new widget.Label();
        buttonCariPoli = new widget.Button();
        namaPoli = new widget.TextField();
        jLabel36 = new widget.Label();
        buttonCariDokter = new widget.Button();
        namaDokter = new widget.TextField();
        jLabel11 = new widget.Label();
        namaPasien = new widget.Label();
        jLabel19 = new widget.Label();
        tglLahir = new widget.Label();
        tanggalPeriksa = new widget.Label();
        jenisBayar = new widget.Label();
        emptyKanan = new widget.Panel();
        panelBawah = new widget.Panel();
        btnSimpan = new widget.Button();
        btnKeluar = new widget.Button();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panelAtas.setPreferredSize(new java.awt.Dimension(1, 35));
        panelAtas.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));

        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("PENDAFTARAN POLIKLINIK EKSEKUTIF");
        label1.setFocusable(false);
        label1.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        label1.setPreferredSize(new java.awt.Dimension(600, 30));
        panelAtas.add(label1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        getContentPane().add(panelAtas, gridBagConstraints);

        emptyKiri.setMinimumSize(new java.awt.Dimension(0, 0));
        emptyKiri.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(emptyKiri, gridBagConstraints);

        panelTengah.setPreferredSize(new java.awt.Dimension(880, 410));
        panelTengah.setLayout(null);

        jLabel10.setText("No. Rekam Medis :");
        jLabel10.setPreferredSize(new java.awt.Dimension(20, 14));
        panelTengah.add(jLabel10);
        jLabel10.setBounds(0, 50, 165, 40);

        jLabel29.setText("Tanggal Periksa :");
        jLabel29.setPreferredSize(new java.awt.Dimension(20, 14));
        panelTengah.add(jLabel29);
        jLabel29.setBounds(0, 200, 165, 40);

        jLabel31.setText("Poli Tujuan :");
        jLabel31.setPreferredSize(new java.awt.Dimension(20, 14));
        panelTengah.add(jLabel31);
        jLabel31.setBounds(0, 250, 165, 40);

        noRM.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        noRM.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        noRM.setPreferredSize(new java.awt.Dimension(20, 14));
        panelTengah.add(noRM);
        noRM.setBounds(175, 50, 650, 40);

        jLabel32.setText("Dokter Tujuan :");
        jLabel32.setPreferredSize(new java.awt.Dimension(20, 14));
        panelTengah.add(jLabel32);
        jLabel32.setBounds(0, 300, 165, 40);

        buttonCariPoli.setBackground(new java.awt.Color(240, 249, 255));
        buttonCariPoli.setBorder(null);
        buttonCariPoli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/pilih.png"))); // NOI18N
        buttonCariPoli.setToolTipText("Alt+S");
        buttonCariPoli.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        buttonCariPoli.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buttonCariPoli.setPreferredSize(new java.awt.Dimension(300, 45));
        buttonCariPoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariPoliActionPerformed(evt);
            }
        });
        panelTengah.add(buttonCariPoli);
        buttonCariPoli.setBounds(830, 250, 45, 40);

        namaPoli.setEditable(false);
        namaPoli.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        namaPoli.setPreferredSize(new java.awt.Dimension(72, 28));
        panelTengah.add(namaPoli);
        namaPoli.setBounds(175, 250, 650, 40);

        jLabel36.setText("Cara Bayar :");
        jLabel36.setPreferredSize(new java.awt.Dimension(20, 14));
        panelTengah.add(jLabel36);
        jLabel36.setBounds(0, 350, 165, 40);

        buttonCariDokter.setBackground(new java.awt.Color(240, 249, 255));
        buttonCariDokter.setBorder(null);
        buttonCariDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/pilih.png"))); // NOI18N
        buttonCariDokter.setToolTipText("Alt+S");
        buttonCariDokter.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        buttonCariDokter.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buttonCariDokter.setPreferredSize(new java.awt.Dimension(300, 45));
        buttonCariDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariDokterActionPerformed(evt);
            }
        });
        panelTengah.add(buttonCariDokter);
        buttonCariDokter.setBounds(830, 300, 45, 40);

        namaDokter.setEditable(false);
        namaDokter.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        namaDokter.setPreferredSize(new java.awt.Dimension(72, 28));
        panelTengah.add(namaDokter);
        namaDokter.setBounds(175, 300, 650, 40);

        jLabel11.setText("Nama Pasien :");
        jLabel11.setPreferredSize(new java.awt.Dimension(20, 14));
        panelTengah.add(jLabel11);
        jLabel11.setBounds(0, 100, 165, 40);

        namaPasien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaPasien.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        namaPasien.setPreferredSize(new java.awt.Dimension(20, 14));
        panelTengah.add(namaPasien);
        namaPasien.setBounds(175, 100, 650, 40);

        jLabel19.setText("Tgl. Lahir :");
        jLabel19.setPreferredSize(new java.awt.Dimension(20, 14));
        panelTengah.add(jLabel19);
        jLabel19.setBounds(0, 150, 165, 40);

        tglLahir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tglLahir.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        tglLahir.setPreferredSize(new java.awt.Dimension(20, 14));
        panelTengah.add(tglLahir);
        tglLahir.setBounds(175, 150, 650, 40);

        tanggalPeriksa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tanggalPeriksa.setText(DateTimeFormatter.ofPattern("yyyy-MM-dd").format(LocalDate.now()));
        tanggalPeriksa.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        tanggalPeriksa.setPreferredSize(new java.awt.Dimension(20, 14));
        panelTengah.add(tanggalPeriksa);
        tanggalPeriksa.setBounds(175, 200, 650, 40);

        jenisBayar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jenisBayar.setText("UMUM / PERSONAL");
        jenisBayar.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jenisBayar.setPreferredSize(new java.awt.Dimension(20, 14));
        panelTengah.add(jenisBayar);
        jenisBayar.setBounds(175, 350, 590, 40);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(panelTengah, gridBagConstraints);

        emptyKanan.setMinimumSize(new java.awt.Dimension(0, 0));
        emptyKanan.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(emptyKanan, gridBagConstraints);

        panelBawah.setPreferredSize(new java.awt.Dimension(1, 75));
        panelBawah.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 0));

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/konfirmasi.png"))); // NOI18N
        btnSimpan.setText("KONFIRMASI");
        btnSimpan.setToolTipText("Alt+S");
        btnSimpan.setPreferredSize(new java.awt.Dimension(300, 60));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        panelBawah.add(btnSimpan);

        btnKeluar.setBackground(new java.awt.Color(255, 255, 255));
        btnKeluar.setForeground(new java.awt.Color(255, 33, 32));
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/exit.png"))); // NOI18N
        btnKeluar.setText("Batal");
        btnKeluar.setToolTipText("Alt+K");
        btnKeluar.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        btnKeluar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnKeluar.setPreferredSize(new java.awt.Dimension(300, 60));
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        panelBawah.add(btnKeluar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        getContentPane().add(panelBawah, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        emptTeks();
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if (noRM.getText().isBlank()) {
            Valid.popupInfoDialog("No. RM Kosong..!!");
        } else if (kdPoli.isBlank()) {
            Valid.popupInfoDialog("Pilih poli terlebih dahulu..!!");
        } else if (kdDokter.isBlank()) {
            Valid.popupInfoDialog("Pilih Dokter terlebih dahulu..!!");
        } else if (Sequel.cariExistsSmc("select * from reg_periksa where kd_pj = 'A09' and no_rkm_medis = ? and tgl_registrasi = current_date() and kd_poli = ? and kd_dokter = ?", noRM.getText(), kdPoli, kdDokter)) {
            Valid.popupInfoDialog("Maaf, anda sudah terdaftar pada hari ini dengan dokter dan poli yang sama..!!");
        } else if (Sequel.cariExistsSmc("select * from reg_periksa join kamar_inap on reg_periksa.no_rawat = kamar_inap.no_rawat where kamar_inap.stts_pulang = '-' and reg_periksa.no_rkm_medis = ?", noRM.getText())) {
            Valid.popupInfoDialog("Maaf, pasien sedang dalam masa perawatan di rawat inap..!!");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            int next = 0, retries = 5;
            boolean sukses = false;

            String waktu = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new java.util.Date());

            do {
                autonomor();
                System.out.print("Mencoba mendaftarkan pasien dengan no. rawat [" + noRawat + "] : ");
                biayaReg = statusPoli.equals("Lama") ? poliBiayaLama : poliBiaya;

                sukses = Sequel.menyimpantfSmc("reg_periksa", null, noReg, noRawat,
                    waktu.substring(0, 10), waktu.substring(11), kdDokter, noRM.getText(),
                    kdPoli, namaPJ, alamatPJ, hubunganPJ, biayaReg, "Belum", statusDaftar,
                    "Ralan", "A09", umurDaftar, statusUmur, "Belum Bayar", statusPoli
                );

                if (!sukses) {
                    System.out.println("Gagal!");
                }
            } while (next++ < retries && !sukses);

            if (sukses) {
                System.out.println("Berhasil!");
                Sequel.mengupdateSmc("pasien", "umur = ?", "no_rkm_medis = ?", umurPasien, noRM.getText());

                Map<String, Object> param = new HashMap<>();
                param.put("namars", instansiNama);
                param.put("alamatrs", instansiAlamat);
                param.put("kotars", instansiKota);
                param.put("kontakrs", instansiKontak);
                param.put("norawat", noRawat);
                Valid.printReportSmc("rptBarcodeRawatAPM.jasper", "report", "::[ Barcode Perawatan ]::", param, printerBarcode, printJumlahBarcode);
                Valid.popupInfoDialog("Berhasil!");
            } else {
                Valid.popupInfoDialog("Pendaftaran gagal..!!\nSilahkan coba kembali.");
            }
            this.setCursor(Cursor.getDefaultCursor());
            btnKeluarActionPerformed(null);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void buttonCariDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariDokterActionPerformed
        dokter.setSize(getContentPane().getSize());
        dokter.setLocationRelativeTo(getContentPane());
        dokter.tampil(hari, kdPoli);
        dokter.setVisible(true);
    }//GEN-LAST:event_buttonCariDokterActionPerformed

    private void buttonCariPoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariPoliActionPerformed
        poli.setSize(getContentPane().getSize());
        poli.setLocationRelativeTo(getContentPane());
        poli.setHari(hari);
        poli.setVisible(true);
    }//GEN-LAST:event_buttonCariPoliActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        loadPengaturanAPM();
    }//GEN-LAST:event_formWindowActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button btnKeluar;
    private widget.Button btnSimpan;
    private widget.Button buttonCariDokter;
    private widget.Button buttonCariPoli;
    private widget.Panel emptyKanan;
    private widget.Panel emptyKiri;
    private widget.Label jLabel10;
    private widget.Label jLabel11;
    private widget.Label jLabel19;
    private widget.Label jLabel29;
    private widget.Label jLabel31;
    private widget.Label jLabel32;
    private widget.Label jLabel36;
    private widget.Label jenisBayar;
    private widget.Label label1;
    private widget.TextField namaDokter;
    private widget.Label namaPasien;
    private widget.TextField namaPoli;
    private widget.Label noRM;
    private widget.Panel panelAtas;
    private widget.Panel panelBawah;
    private widget.Panel panelTengah;
    private widget.Label tanggalPeriksa;
    private widget.Label tglLahir;
    // End of variables declaration//GEN-END:variables

    public void setPasien(String noRM) {
        tentukanHari();

        if (Sequel.cariExistsSmc("select * from reg_periksa where no_rkm_medis = ? and kd_poli = ?", noRM, kdPoli)) {
            statusPoli = "Lama";
        }

        try (PreparedStatement ps = koneksi.prepareStatement(
            "select pasien.nm_pasien, concat_ws(', ', pasien.alamat, kelurahan.nm_kel, kecamatan.nm_kec, kabupaten.nm_kab) as alamat, " +
            "pasien.tgl_lahir, pasien.namakeluarga, pasien.keluarga, pasien.kd_pj, if(pasien.tgl_daftar = current_date(), 'baru', 'lama') as daftar, " +
            "timestampdiff(year, pasien.tgl_lahir, current_date()) as tahun, timestampdiff(month, pasien.tgl_lahir, current_date()) - ((timestampdiff(month, " +
            "pasien.tgl_lahir, current_date()) div 12) * 12) as bulan, timestampdiff(day, date_add(date_add(pasien.tgl_lahir, interval timestampdiff(year, " +
            "pasien.tgl_lahir, current_date()) year), interval timestampdiff(month, pasien.tgl_lahir, current_date()) - ((timestampdiff(month, pasien.tgl_lahir, " +
            "current_date()) div 12) * 12) month), current_date()) as hari from pasien join kelurahan on pasien.kd_kel = kelurahan.kd_kel join kecamatan on " +
            "pasien.kd_kec = kecamatan.kd_kec join kabupaten on pasien.kd_kab = kabupaten.kd_kab where pasien.no_rkm_medis = ?"
        )) {
            ps.setString(1, noRM);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    this.noRM.setText(noRM);
                    namaPasien.setText(rs.getString("nm_pasien"));
                    tglLahir.setText(DateTimeFormatter.ofPattern("dd MMMM yyyy").withLocale(new Locale("id", "ID")).format(rs.getDate("tgl_lahir").toLocalDate()));
                    namaPJ = rs.getString("namakeluarga");
                    alamatPJ = rs.getString("alamat");
                    hubunganPJ = rs.getString("keluarga");
                    statusDaftar = rs.getString("daftar");
                    if (rs.getInt("tahun") > 0) {
                        umurDaftar = rs.getString("tahun");
                        statusUmur = "Th";
                    } else if ((rs.getInt("tahun") <= 0) && (rs.getInt("bulan") > 0)) {
                        umurDaftar = rs.getString("bulan");
                        statusUmur = "Bl";
                    } else if ((rs.getInt("tahun") <= 0) && (rs.getInt("bulan") <= 0) && (rs.getInt("hari") > 0)) {
                        umurDaftar = rs.getString("hari");
                        statusUmur = "Hr";
                    }
                    umurPasien = rs.getString("tahun") + " Th " + rs.getString("bulan") + " Bl " + rs.getString("hari") + " Hr";
                }
            }
        } catch (SQLException e) {
            System.out.println("Notif : " + e);
        }
    }

    private void autonomor() {
        switch (URUTNOREG) {
            case "poli":
                noReg = Sequel.cariIsiSmc("select lpad(ifnull(max(convert(no_reg, signed)), 0) + 1, 3, '0') from reg_periksa where kd_poli = ? and tgl_registrasi = current_date()", kdPoli);
                break;
            case "dokter":
                noReg = Sequel.cariIsiSmc("select lpad(ifnull(max(convert(no_reg, signed)), 0) + 1, 3, '0') from reg_periksa where kd_dokter = ? and tgl_registrasi = current_date()", kdDokter);
                break;
            case "dokter + poli":
                noReg = Sequel.cariIsiSmc("select lpad(ifnull(max(convert(no_reg, signed)), 0) + 1, 3, '0') from reg_periksa where kd_poli = ? and kd_dokter = ? and tgl_registrasi = current_date()", kdPoli, kdDokter);
                break;
            default:
                noReg = Sequel.cariIsiSmc("select lpad(ifnull(max(convert(no_reg, signed)), 0) + 1, 3, '0') from reg_periksa where kd_poli = ? and kd_dokter = ? and tgl_registrasi = current_date()", kdPoli, kdDokter);
                break;
        }
        noRawat = Sequel.cariIsiSmc("select concat(date_format(current_date(), '%Y/%m/%d'), '/', lpad(ifnull(max(convert(right(no_rawat, 6), signed)), 0) + 1, 6, '0')) from reg_periksa where tgl_registrasi = current_date()");
    }

    private void tentukanHari() {
        try {
            switch (Calendar.getInstance().get(Calendar.DAY_OF_WEEK)) {
                case 1:
                    hari = "AKHAD";
                    break;
                case 2:
                    hari = "SENIN";
                    break;
                case 3:
                    hari = "SELASA";
                    break;
                case 4:
                    hari = "RABU";
                    break;
                case 5:
                    hari = "KAMIS";
                    break;
                case 6:
                    hari = "JUMAT";
                    break;
                case 7:
                    hari = "SABTU";
                    break;
                default:
                    break;
            }

        } catch (Exception e) {
            System.out.println("Notif : " + e);
        }
    }

    private void emptTeks() {
        hari = "";
        noRawat = "";
        noReg = "";
        kdDokter = "";
        kdPoli = kodePoliEksekutif.isBlank() ? "" : kodePoliEksekutif;
        biayaReg = "";
        statusDaftar = "Lama";
        statusPoli = "Baru";
        umurDaftar = "0";
        statusUmur = "Th";
        namaPJ = "-";
        hubunganPJ = "-";
        alamatPJ = "-";
        instansiNama = "";
        instansiAlamat = "";
        instansiKota = "";
        instansiKontak = "";

        noRM.setText("");
        namaPasien.setText("");
        tglLahir.setText("");
        tanggalPeriksa.setText(DateTimeFormatter.ofPattern("yyyy-MM-dd").format(LocalDate.now()));
        namaPoli.setText(Sequel.cariIsiSmc("select poliklinik.nm_poli from poliklinik where poliklinik.kd_poli = ?", kdPoli));
        namaDokter.setText("");
    }

    private void loadPengaturanAPM() {
        if (new File("./cache/pengaturanapmsmc.iyem").isFile()) {
            try (FileReader fr = new FileReader("./cache/pengaturanapmsmc.iyem")) {
                final ObjectMapper mapper = new ObjectMapper();
                final JsonNode root = mapper.readTree(fr).path("pengaturanapmsmc");
                final JsonNode decrypted = mapper.readTree(EnkripsiAES.decrypt(root.asText()));

                if (decrypted.hasNonNull("kodePoliEksekutif")) {
                    if (decrypted.path("kodePoliEksekutif").isArray()) {
                        long count = StreamSupport.stream(decrypted.withArray("kodePoliEksekutif").spliterator(), false).count();
                        if (count == 1) {
                            kodePoliEksekutif = decrypted.withArray("kodePoliEksekutif").iterator().next().asText();
                        } else {
                            kodePoliEksekutif = "";
                        }
                    } else {
                        kodePoliEksekutif = decrypted.path("kodePoliEksekutif").asText();
                    }
                }

                if (decrypted.hasNonNull("printerBarcode")) {
                    printerBarcode = decrypted.path("printerBarcode").asText();
                }

                if (decrypted.hasNonNull("printJumlahBarcode")) {
                    printJumlahBarcode = decrypted.path("printJumlahBarcode").asInt(0);
                }
            } catch (Exception e) {
                System.out.println("Notif : " + e);
            }
        } else {
            kodePoliEksekutif = koneksiDB.KODEPOLIEKSEKUTIF().length > 0 ? koneksiDB.KODEPOLIEKSEKUTIF()[0] : "";
            printerBarcode = koneksiDB.PRINTER_BARCODE();
            printJumlahBarcode = koneksiDB.PRINTJUMLAHBARCODE();
        }

        if (kodePoliEksekutif.isBlank()) {
            buttonCariPoli.setVisible(true);
            poli.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    if (poli.hasSelection()) {
                        namaDokter.setText("");
                        kdDokter = "";
                        kdPoli = poli.getSelectedRow(0).toString();
                        namaPoli.setText(poli.getSelectedRow(1).toString());
                        poliBiaya = poli.getSelectedRow(2).toString();
                        poliBiayaLama = poli.getSelectedRow(3).toString();
                    }
                }
            });
        } else {
            buttonCariPoli.setVisible(false);
            kdPoli = kodePoliEksekutif;
            namaPoli.setText(Sequel.cariIsiSmc("select poliklinik.nm_poli from poliklinik where poliklinik.kd_poli = ?", kdPoli));
            poliBiaya = Sequel.cariIsiSmc("select poliklinik.registrasi from poliklinik where poliklinik.kd_poli = ?", kdPoli);
            poliBiayaLama = Sequel.cariIsiSmc("select poliklinik.registrasilama from poliklinik where poliklinik.kd_poli = ?", kdPoli);
        }
    }
}
