package khanzahmsanjungan;

import fungsi.koneksiDB;
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author it-rsib
 */
public class HalamanUtama extends javax.swing.JFrame {

    private final ArrayList<String> TOMBOLDIMATIKAN = new ArrayList(Arrays.asList(koneksiDB.TOMBOLDIMATIKAN()));
    private DlgCekDataPasien umum = null;
    private DlgCekDataBPJS bpjs = null;
    private DlgAmbilAntrian antrian = null;
    private DlgAmbilAntrianFarmasi antrianfarmasi = null;

    public HalamanUtama() {
        initComponents();
        setIconImage(new ImageIcon(super.getClass().getResource("/picture/logo.png")).getImage());
        
        TOMBOLDIMATIKAN.forEach(tombol -> {
            switch (tombol) {
                case "antrian":
                    panelTengah.remove(btnAntrian);
                    break;
                case "antrianfarmasi":
                    panelTengah.remove(btnAntrianFarmasi);
                    break;
                case "cekin":
                    panelTengah.remove(btnBooking);
                    break;
                case "daftarpoli":
                    panelTengah.remove(btnDaftarpoli);
                    break;
                case "seppertama":
                    panelTengah.remove(btnSEPPertama);
                    break;
                case "sepkontrol":
                    panelTengah.remove(btnSEPKontrol);
                    break;
                case "sepbedapoli":
                    panelTengah.remove(btnSEPKontrolBedaPoli);
                    break;
                case "mobilejkn":
                    panelTengah.remove(btnMobilejkn);
                    break;
                case "satusehat":
                    panelTengah.remove(btnSatusehat);
                    break;
            }
        });

        if (panelTengah.getComponentCount() == 1) {
            panelTengah.setLayout(new java.awt.GridLayout(0, 1));
        }

        panelTengah.repaint();

        pack();

        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAtas = new widget.Panel();
        flatLabel1 = new com.formdev.flatlaf.extras.components.FlatLabel();
        panelTengah = new widget.Panel();
        btnAntrian = new widget.MenuButton();
        btnAntrianFarmasi = new widget.MenuButton();
        btnBooking = new widget.MenuButton();
        btnDaftarpoli = new widget.MenuButton();
        btnSEPPertama = new widget.MenuButton();
        btnSEPKontrol = new widget.MenuButton();
        btnSEPKontrolBedaPoli = new widget.MenuButton();
        btnMobilejkn = new widget.MenuButton();
        btnSatusehat = new widget.MenuButton();
        panelBawah = new widget.Panel();
        versi = new widget.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ANJUNGAN PASIEN MANDIRI");
        setBackground(new java.awt.Color(102, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        panelAtas.setMinimumSize(new java.awt.Dimension(500, 100));
        panelAtas.setPreferredSize(new java.awt.Dimension(500, 100));
        panelAtas.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 10));

        flatLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/logocokro (2).png"))); // NOI18N
        panelAtas.add(flatLabel1);

        getContentPane().add(panelAtas, java.awt.BorderLayout.PAGE_START);

        panelTengah.setPreferredSize(new java.awt.Dimension(1280, 1024));
        panelTengah.setLayout(new java.awt.GridLayout(0, 2));

        btnAntrian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/antrianpasien.png"))); // NOI18N
        btnAntrian.setText("ANTRIAN LOKET PENDAFTARAN");
        btnAntrian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAntrianActionPerformed(evt);
            }
        });
        panelTengah.add(btnAntrian);

        btnAntrianFarmasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/farmasi.png"))); // NOI18N
        btnAntrianFarmasi.setText("ANTRIAN RESEP FARMASI");
        btnAntrianFarmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAntrianFarmasiActionPerformed(evt);
            }
        });
        panelTengah.add(btnAntrianFarmasi);

        btnBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/checkin.png"))); // NOI18N
        btnBooking.setText("CEK IN BOOKING");
        btnBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingActionPerformed(evt);
            }
        });
        panelTengah.add(btnBooking);

        btnDaftarpoli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/kioskselfservice.png"))); // NOI18N
        btnDaftarpoli.setText("PENDAFTARAN EKSEKUTIF");
        btnDaftarpoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarpoliActionPerformed(evt);
            }
        });
        panelTengah.add(btnDaftarpoli);

        btnSEPPertama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/bpjs_kesehatan.png"))); // NOI18N
        btnSEPPertama.setText("SEP KUNJUNGAN PERTAMA");
        btnSEPPertama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSEPPertamaActionPerformed(evt);
            }
        });
        panelTengah.add(btnSEPPertama);

        btnSEPKontrol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/bpjs_kesehatan.png"))); // NOI18N
        btnSEPKontrol.setText("SEP KONTROL");
        btnSEPKontrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSEPKontrolActionPerformed(evt);
            }
        });
        panelTengah.add(btnSEPKontrol);

        btnSEPKontrolBedaPoli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/bpjs_kesehatan.png"))); // NOI18N
        btnSEPKontrolBedaPoli.setText("KONTROL BEDA POLI");
        btnSEPKontrolBedaPoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSEPKontrolBedaPoliActionPerformed(evt);
            }
        });
        panelTengah.add(btnSEPKontrolBedaPoli);

        btnMobilejkn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/mobilejkn48.png"))); // NOI18N
        btnMobilejkn.setText("CEK IN MOBILEJKN");
        btnMobilejkn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMobilejknActionPerformed(evt);
            }
        });
        panelTengah.add(btnMobilejkn);

        btnSatusehat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/logo-satset.png"))); // NOI18N
        btnSatusehat.setText("AKTIVASI SATUSEHAT");
        btnSatusehat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSatusehatActionPerformed(evt);
            }
        });
        panelTengah.add(btnSatusehat);

        getContentPane().add(panelTengah, java.awt.BorderLayout.CENTER);

        panelBawah.setLayout(new java.awt.BorderLayout());

        versi.setForeground(new java.awt.Color(150, 155, 159));
        versi.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        versi.setText("Build 2025-08-29 Patch 1      ");
        versi.setFocusable(false);
        versi.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        versi.setPreferredSize(new java.awt.Dimension(1, 20));
        panelBawah.add(versi, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(panelBawah, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSEPKontrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSEPKontrolActionPerformed
        if (bpjs == null) {
            bpjs = new DlgCekDataBPJS(this, false);
        }
        bpjs.setFlag(DlgCekDataBPJS.SEP_KONTROL);
        bpjs.setSize(getContentPane().getSize());
        bpjs.setLocationRelativeTo(getContentPane());
        bpjs.setVisible(true);
    }//GEN-LAST:event_btnSEPKontrolActionPerformed

    private void btnBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingActionPerformed
        if (!koneksiDB.BOOKINGLANGSUNGREGISTRASI()) {
            JOptionPane.showMessageDialog(null, "Mohon maaf, fitur masih dalam tahap pengembangan");
        } else {
            if (umum == null) {
                umum = new DlgCekDataPasien(this, false);
            }
            umum.setFlag(DlgCekDataPasien.CEKIN_BOOKING);
            umum.setSize(getContentPane().getSize());
            umum.setLocationRelativeTo(getContentPane());
            umum.setVisible(true);
        }
    }//GEN-LAST:event_btnBookingActionPerformed

    private void btnSEPPertamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSEPPertamaActionPerformed
        if (bpjs == null) {
            bpjs = new DlgCekDataBPJS(this, false);
        }
        bpjs.setFlag(DlgCekDataBPJS.SEP_KUNJUNGAN_PERTAMA);
        bpjs.setSize(getContentPane().getSize());
        bpjs.setLocationRelativeTo(getContentPane());
        bpjs.setVisible(true);
    }//GEN-LAST:event_btnSEPPertamaActionPerformed

    private void btnMobilejknActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMobilejknActionPerformed
        if (bpjs == null) {
            bpjs = new DlgCekDataBPJS(this, false);
        }
        bpjs.setFlag(DlgCekDataBPJS.SEP_MOBILEJKN);
        bpjs.setSize(getContentPane().getSize());
        bpjs.setLocationRelativeTo(getContentPane());
        bpjs.setVisible(true);
    }//GEN-LAST:event_btnMobilejknActionPerformed

    private void btnSEPKontrolBedaPoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSEPKontrolBedaPoliActionPerformed
        if (bpjs == null) {
            bpjs = new DlgCekDataBPJS(this, false);
        }
        bpjs.setFlag(DlgCekDataBPJS.SEP_KONTROL_BEDA_POLI);
        bpjs.setSize(getContentPane().getSize());
        bpjs.setLocationRelativeTo(getContentPane());
        bpjs.setVisible(true);
    }//GEN-LAST:event_btnSEPKontrolBedaPoliActionPerformed

    private void btnAntrianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAntrianActionPerformed
        if (koneksiDB.ANTRIANPREFIXHURUF()) {
            if (antrian == null) {
                antrian = new DlgAmbilAntrian(this, false);
            }
            antrian.setSize(getContentPane().getSize());
            antrian.setLocationRelativeTo(getContentPane());
            antrian.setVisible(true);
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            try {
                Runtime.getRuntime().exec("java -jar KhanzaCetakAntrianLoket.jar");
            } catch (Exception e) {
                System.out.print("Notif : " + e);
            }
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnAntrianActionPerformed

    private void btnSatusehatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSatusehatActionPerformed
        JOptionPane.showMessageDialog(null, "Mohon maaf, fitur masih dalam tahap pengembangan");
        // this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        // String nikktppetugas = Sequel.cariIsi("select no_ktp from pegawai where nik='0132' ");
        // Valid.panggilUrl("kyc/index.php?&nikagent=" + nikktppetugas + "");
        // this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_btnSatusehatActionPerformed

    private void btnAntrianFarmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAntrianFarmasiActionPerformed
        if (antrianfarmasi == null) {
            antrianfarmasi = new DlgAmbilAntrianFarmasi(this, false);
        }
        antrianfarmasi.setSize(getContentPane().getSize());
        antrianfarmasi.setLocationRelativeTo(getContentPane());
        antrianfarmasi.setVisible(true);
    }//GEN-LAST:event_btnAntrianFarmasiActionPerformed

    private void btnDaftarpoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarpoliActionPerformed
        if (umum == null) {
            umum = new DlgCekDataPasien(this, false);
        }
        umum.setFlag(DlgCekDataPasien.REGIST_MANDIRI);
        umum.setSize(getContentPane().getSize());
        umum.setLocationRelativeTo(getContentPane());
        umum.setVisible(true);
    }//GEN-LAST:event_btnDaftarpoliActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.MenuButton btnAntrian;
    private widget.MenuButton btnAntrianFarmasi;
    private widget.MenuButton btnBooking;
    private widget.MenuButton btnDaftarpoli;
    private widget.MenuButton btnMobilejkn;
    private widget.MenuButton btnSEPKontrol;
    private widget.MenuButton btnSEPKontrolBedaPoli;
    private widget.MenuButton btnSEPPertama;
    private widget.MenuButton btnSatusehat;
    private com.formdev.flatlaf.extras.components.FlatLabel flatLabel1;
    private widget.Panel panelAtas;
    private widget.Panel panelBawah;
    private widget.Panel panelTengah;
    private widget.Label versi;
    // End of variables declaration//GEN-END:variables
}
