/*
  Dilarang keras menggandakan/mengcopy/menyebarkan/membajak/mendecompile
  Software ini dalam bentuk apapun tanpa seijin pembuat software
  (Khanza.Soft Media). Bagi yang sengaja membajak softaware ini ta
  npa ijin, kami sumpahi sial 1000 turunan, miskin sampai 500 turu
  nan. Selalu mendapat kecelakaan sampai 400 turunan. Anak pertama
  nya cacat tidak punya kaki sampai 300 turunan. Susah cari jodoh
  sampai umur 50 tahun sampai 200 turunan. Ya Alloh maafkan kami
  karena telah berdoa buruk, semua ini kami lakukan karena kami ti
  dak pernah rela karya kami dibajak tanpa ijin.
 */
package bridging;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import fungsi.validasi;
import fungsi.koneksiDB;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import java.util.List;
import java.util.stream.StreamSupport;
import javax.swing.SwingWorker;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;

/**
 *
 * @author dosen
 */
public final class BPJSRiwayatPelayananPasien extends widget.Dialog {
    private final DefaultTableModel tabMode;
    private final validasi Valid = new validasi();
    private final ApiBPJS api = new ApiBPJS();
    private volatile boolean isLoading = false;
    private boolean isOpened = false;
    private String noPeserta = "";

    /**
     * Creates new form DlgKamar
     *
     * @param parent
     * @param modal
     */
    public BPJSRiwayatPelayananPasien(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        tabMode = new DefaultTableModel(null, new Object[] {
            "No.", "Diagnosa", "Jenis Pelayanan", "Kelas Rawat", "Nama Peserta", "No. Kartu",
            "No. SEP", "No.Rujukan", "Poli", "PPK Pelayanan", "Pulang SEP", "Tgl. SEP"
        }) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        tbRiwayat.setModel(tabMode);

        for (int i = 0; i < 12; i++) {
            TableColumn column = tbRiwayat.getColumnModel().getColumn(i);
            if (i == 0) {
                column.setPreferredWidth(50);
            } else if (i == 1) {
                column.setPreferredWidth(230);
            } else if (i == 2) {
                column.setPreferredWidth(150);
            } else if (i == 3) {
                column.setPreferredWidth(150);
            } else if (i == 4) {
                column.setPreferredWidth(160);
            } else if (i == 5) {
                column.setPreferredWidth(150);
            } else if (i == 6) {
                column.setPreferredWidth(125);
            } else if (i == 7) {
                column.setPreferredWidth(200);
            } else if (i == 8) {
                column.setPreferredWidth(115);
            } else if (i == 9) {
                column.setPreferredWidth(160);
            } else if (i == 10) {
                column.setPreferredWidth(150);
            } else if (i == 11) {
                column.setPreferredWidth(150);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Scroll = new widget.ScrollPane();
        tbRiwayat = new widget.Table();
        panelBawah = new widget.Panel();
        BtnKeluar = new widget.Button();
        jLabel19 = new widget.Label();
        DTPCari1 = new widget.Tanggal();
        jLabel21 = new widget.Label();
        DTPCari2 = new widget.Tanggal();
        BtnCari = new widget.Button();
        jLabel17 = new widget.Label();
        jLabel29 = new widget.Label();

        setIconImage(null);
        setIconImages(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Scroll.setName("Scroll"); // NOI18N

        tbRiwayat.setToolTipText("Silahkan klik untuk memilih data yang mau diedit ataupun dihapus");
        tbRiwayat.setName("tbRiwayat"); // NOI18N
        tbRiwayat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbRiwayatMouseReleased(evt);
            }
        });
        Scroll.setViewportView(tbRiwayat);

        getContentPane().add(Scroll, java.awt.BorderLayout.CENTER);

        panelBawah.setName("panelBawah"); // NOI18N
        panelBawah.setPreferredSize(new java.awt.Dimension(44, 68));
        panelBawah.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        BtnKeluar.setBackground(new java.awt.Color(255, 255, 255));
        BtnKeluar.setForeground(new java.awt.Color(255, 23, 26));
        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/exit.png"))); // NOI18N
        BtnKeluar.setText("KELUAR");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        panelBawah.add(BtnKeluar);

        jLabel19.setText("Periode :");
        jLabel19.setName("jLabel19"); // NOI18N
        jLabel19.setPreferredSize(new java.awt.Dimension(95, 36));
        panelBawah.add(jLabel19);

        DTPCari1.setEditable(false);
        DTPCari1.setName("DTPCari1"); // NOI18N
        DTPCari1.setOpaque(false);
        DTPCari1.setPreferredSize(new java.awt.Dimension(140, 36));
        panelBawah.add(DTPCari1);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("s.d.");
        jLabel21.setName("jLabel21"); // NOI18N
        jLabel21.setPreferredSize(new java.awt.Dimension(50, 36));
        panelBawah.add(jLabel21);

        DTPCari2.setEditable(false);
        DTPCari2.setName("DTPCari2"); // NOI18N
        DTPCari2.setOpaque(false);
        DTPCari2.setPreferredSize(new java.awt.Dimension(140, 36));
        panelBawah.add(DTPCari2);

        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari.setMaximumSize(new java.awt.Dimension(36, 36));
        BtnCari.setMinimumSize(new java.awt.Dimension(36, 36));
        BtnCari.setName("BtnCari"); // NOI18N
        BtnCari.setPreferredSize(new java.awt.Dimension(36, 36));
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        BtnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariKeyPressed(evt);
            }
        });
        panelBawah.add(BtnCari);

        jLabel17.setFocusable(false);
        jLabel17.setName("jLabel17"); // NOI18N
        jLabel17.setPreferredSize(new java.awt.Dimension(40, 30));
        panelBawah.add(jLabel17);

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setText("Klik pada kolom No. SEP apabila ingin mengambil No. SEP");
        jLabel29.setName("jLabel29"); // NOI18N
        jLabel29.setPreferredSize(new java.awt.Dimension(520, 30));
        panelBawah.add(jLabel29);

        getContentPane().add(panelBawah, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnCariActionPerformed(null);
        }
    }//GEN-LAST:event_BtnCariKeyPressed

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
        if (noPeserta.isBlank()) {
            Valid.popupPeringatanDialog("Silahkan pilih data peserta terlebih dahulu..!!");
            dispose();
        } else {
            tampil();
        }
    }//GEN-LAST:event_BtnCariActionPerformed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void tbRiwayatMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRiwayatMouseReleased
        dispose();
    }//GEN-LAST:event_tbRiwayatMouseReleased

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (!isOpened) {
            tampil();
            isOpened = true;
        }
    }//GEN-LAST:event_formWindowActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnCari;
    private widget.Button BtnKeluar;
    private widget.Tanggal DTPCari1;
    private widget.Tanggal DTPCari2;
    private widget.ScrollPane Scroll;
    private widget.Label jLabel17;
    private widget.Label jLabel19;
    private widget.Label jLabel21;
    private widget.Label jLabel29;
    private widget.Panel panelBawah;
    private widget.Table tbRiwayat;
    // End of variables declaration//GEN-END:variables

    private void tampil() {
        if (!isLoading) {
            isLoading = true;
            Valid.tabelKosongSmc(tabMode);
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

            new SwingWorker<Void, Object[]>() {
                private final String tglAwal = Valid.getTglSmc(DTPCari1);
                private final String tglAkhir = Valid.getTglSmc(DTPCari2);
                private volatile int i = 0;
                private String pesan = null;

                @Override
                protected Void doInBackground() throws Exception {
                    HttpHeaders headers = new HttpHeaders();
                    String utc = api.getUTCDateTimeAsString();
                    headers.setContentType(MediaType.APPLICATION_JSON);
                    headers.add("X-Cons-ID", koneksiDB.CONSIDAPIBPJS());
                    headers.add("X-Timestamp", utc);
                    headers.add("X-Signature", api.getHmac(utc));
                    headers.add("user_key", koneksiDB.USERKEYAPIBPJS());

                    final ObjectMapper mapper = new ObjectMapper();
                    JsonNode root = mapper.readTree(api.getRest().exchange(
                        koneksiDB.URLAPIBPJS() + "/monitoring/HistoriPelayanan/NoKartu/" + noPeserta + "/tglMulai/" + tglAwal + "/tglAkhir/" + tglAkhir,
                        HttpMethod.GET, new HttpEntity(headers), String.class).getBody());
                    JsonNode metadata = root.path("metaData");

                    if (metadata.path("code").asText().equals("200")) {
                        JsonNode response = mapper.readTree(api.Decrypt(root.path("response").asText(), utc));
                        if (response.path("histori").isArray()) {
                            StreamSupport.stream(response.path("histori").spliterator(), false)
                                .forEach(list -> publish(new Object[] {
                                    (++i), list.path("diagnosa").asText(), list.path("jnsPelayanan").asText().replaceAll("1", "Rawat Inap").replaceAll("2", "Rawat Jalan"),
                                    list.path("kelasRawat").asText(), list.path("namaPeserta").asText(), list.path("noKartu").asText(), list.path("noSep").asText(),
                                    list.path("noRujukan").asText(), list.path("poli").asText(), list.path("ppkPelayanan").asText(), list.path("tglPlgSep").asText(),
                                    list.path("tglSep").asText()
                                }));
                        }
                    } else {
                        pesan = metadata.path("message").asText("");
                    }

                    return null;
                }

                @Override
                protected void process(List<Object[]> chunks) {
                    chunks.forEach(tabMode::addRow);
                }

                @Override
                protected void done() {
                    try {
                        get();
                        if (pesan != null) {
                            Valid.popupPeringatanDialog(pesan);
                        }
                    } catch (Exception e) {
                        System.out.println("Notif : " + e);
                        if (e.toString().contains("UnknownHostException")) {
                            Valid.popupInfoDialog("Koneksi ke server BPJS terputus...!");
                        }
                    }
                    BPJSRiwayatPelayananPasien.this.setCursor(Cursor.getDefaultCursor());
                    isLoading = false;
                }
            }.execute();
        }
    }

    public void setNoPeserta(String noPeserta) {
        this.noPeserta = noPeserta;
        Calendar cal = Calendar.getInstance();
        DTPCari2.setDate(cal.getTime());
        cal.add(Calendar.DAY_OF_MONTH, -90);
        DTPCari1.setDate(cal.getTime());
        this.isOpened = false;
    }

    public JTable getTable() {
        return tbRiwayat;
    }

    public boolean hasSelection() {
        return tbRiwayat.getSelectedRow() >= 0;
    }

    public Object getSelectedRow(int column) {
        return tbRiwayat.getValueAt(tbRiwayat.getSelectedRow(), column);
    }
}
