/*
  Dilarang keras menggandakan/mengcopy/menyebarkan/membajak/mendecompile
  Software ini dalam bentuk apapun tanpa seijin pembuat software
  (Khanza.Soft Media). Bagi yang sengaja membajak softaware ini ta
  npa ijin, kami sumpahi sial 1000 turunan, miskin sampai 500 turu
  nan. Selalu mendapat kecelakaan sampai 400 turunan. Anak pertama
  nya cacat tidak punya kaki sampai 300 turunan. Susah cari jodoh
  sampai umur 50 tahun sampai 200 turunan. Ya Alloh maafkan kami
  karena telah berdoa buruk, semua ini kami lakukan karena kami ti
  dak pernah rela karya kami dibajak tanpa ijin.
 */
package bridging;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import fungsi.koneksiDB;
import fungsi.validasi;
import java.awt.Cursor;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import java.util.stream.StreamSupport;
import javax.swing.JTable;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;

public final class BPJSReferensiDokter extends widget.Dialog {
    private final DefaultTableModel tabMode;
    private final validasi Valid = new validasi();
    private final ApiBPJS api = new ApiBPJS();
    private BPJSReferensiPoli spesialis = null;
    private volatile boolean isLoading = false;
    private boolean isOpened = false;

    public BPJSReferensiDokter(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        tabMode = new DefaultTableModel(null, new String[] {"No.", "Kode Dokter", "Nama Dokter"}) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        tbDokter.setModel(tabMode);

        for (int i = 0; i < 3; i++) {
            TableColumn column = tbDokter.getColumnModel().getColumn(i);
            if (i == 0) {
                column.setPreferredWidth(80);
            } else if (i == 1) {
                column.setPreferredWidth(170);
            } else if (i == 2) {
                column.setPreferredWidth(700);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new widget.Label();
        DTPCari1 = new widget.Tanggal();
        Scroll = new widget.ScrollPane();
        tbDokter = new widget.Table();
        panelBawah = new widget.Panel();
        BtnKeluar = new widget.Button();
        jLabel14 = new widget.Label();
        KdPoli = new widget.TextField();
        NmPoli = new widget.TextField();
        BtnCariPoli = new widget.Button();
        jLabel16 = new widget.Label();
        TCari = new widget.TextField();
        BtnCari = new widget.Button();

        jLabel15.setText("Tanggal Pelayanan :");
        jLabel15.setName("jLabel15"); // NOI18N
        jLabel15.setPreferredSize(new java.awt.Dimension(110, 23));

        DTPCari1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "08-07-2025" }));
        DTPCari1.setName("DTPCari1"); // NOI18N
        DTPCari1.setOpaque(false);
        DTPCari1.setPreferredSize(new java.awt.Dimension(150, 23));

        setIconImage(null);
        setIconImages(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Scroll.setName("Scroll"); // NOI18N

        tbDokter.setName("tbDokter"); // NOI18N
        tbDokter.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbDokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbDokterMouseReleased(evt);
            }
        });
        Scroll.setViewportView(tbDokter);

        getContentPane().add(Scroll, java.awt.BorderLayout.CENTER);

        panelBawah.setName("panelBawah"); // NOI18N
        panelBawah.setPreferredSize(new java.awt.Dimension(44, 68));
        panelBawah.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        BtnKeluar.setBackground(new java.awt.Color(255, 255, 255));
        BtnKeluar.setForeground(new java.awt.Color(255, 23, 26));
        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/exit.png"))); // NOI18N
        BtnKeluar.setText("KELUAR");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        panelBawah.add(BtnKeluar);

        jLabel14.setText("Poli :");
        jLabel14.setName("jLabel14"); // NOI18N
        jLabel14.setPreferredSize(new java.awt.Dimension(61, 36));
        panelBawah.add(jLabel14);

        KdPoli.setEditable(false);
        KdPoli.setName("KdPoli"); // NOI18N
        KdPoli.setPreferredSize(new java.awt.Dimension(100, 36));
        KdPoli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KdPoliKeyPressed(evt);
            }
        });
        panelBawah.add(KdPoli);

        NmPoli.setEditable(false);
        NmPoli.setName("NmPoli"); // NOI18N
        NmPoli.setPreferredSize(new java.awt.Dimension(300, 36));
        NmPoli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NmPoliKeyPressed(evt);
            }
        });
        panelBawah.add(NmPoli);

        BtnCariPoli.setBackground(new java.awt.Color(240, 249, 255));
        BtnCariPoli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/pilih.png"))); // NOI18N
        BtnCariPoli.setMnemonic('3');
        BtnCariPoli.setToolTipText("ALt+3");
        BtnCariPoli.setName("BtnCariPoli"); // NOI18N
        BtnCariPoli.setPreferredSize(new java.awt.Dimension(36, 36));
        BtnCariPoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariPoliActionPerformed(evt);
            }
        });
        BtnCariPoli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariPoliKeyPressed(evt);
            }
        });
        panelBawah.add(BtnCariPoli);

        jLabel16.setText("Key word :");
        jLabel16.setName("jLabel16"); // NOI18N
        jLabel16.setPreferredSize(new java.awt.Dimension(100, 36));
        panelBawah.add(jLabel16);

        TCari.setName("TCari"); // NOI18N
        TCari.setPreferredSize(new java.awt.Dimension(400, 36));
        TCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCariKeyPressed(evt);
            }
        });
        panelBawah.add(TCari);

        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari.setMnemonic('6');
        BtnCari.setToolTipText("Alt+6");
        BtnCari.setMaximumSize(new java.awt.Dimension(30, 30));
        BtnCari.setName("BtnCari"); // NOI18N
        BtnCari.setPreferredSize(new java.awt.Dimension(36, 36));
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        panelBawah.add(BtnCari);

        getContentPane().add(panelBawah, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
        if (KdPoli.getText().trim().equals("") || NmPoli.getText().trim().equals("")) {
            Valid.popupInfoDialog("Silahkan pilih spesialis dulu..!!");
            BtnCariPoli.requestFocus();
        } else {
            tampil();
        }
    }//GEN-LAST:event_BtnCariActionPerformed

    private void BtnCariPoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariPoliActionPerformed
        if (spesialis == null) {
            spesialis = new BPJSReferensiPoli(null, true);
            spesialis.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    if (spesialis.hasSelection()) {
                        KdPoli.setText(spesialis.getSelectedRow(1).toString());
                        NmPoli.setText(spesialis.getSelectedRow(2).toString());
                        BtnCariActionPerformed(null);
                    }
                }
            });

            spesialis.getTable().addKeyListener(new KeyAdapter() {
                @Override
                public void keyPressed(KeyEvent e) {
                    if (e.getKeyCode() == KeyEvent.VK_SPACE) {
                        spesialis.dispose();
                    }
                }
            });
        }
        spesialis.setSize(getContentPane().getSize());
        spesialis.setLocationRelativeTo(getContentPane());
        spesialis.setVisible(true);
    }//GEN-LAST:event_BtnCariPoliActionPerformed

    private void tbDokterMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDokterMouseReleased
        dispose();
    }//GEN-LAST:event_tbDokterMouseReleased

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (!isOpened) {
            BtnCariActionPerformed(null);
            isOpened = true;
        }
    }//GEN-LAST:event_formWindowActivated

    private void TCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BtnCariActionPerformed(null);
        }
    }//GEN-LAST:event_TCariKeyPressed

    private void KdPoliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KdPoliKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BtnCariPoliActionPerformed(null);
        }
    }//GEN-LAST:event_KdPoliKeyPressed

    private void NmPoliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NmPoliKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BtnCariPoliActionPerformed(null);
        }
    }//GEN-LAST:event_NmPoliKeyPressed

    private void BtnCariPoliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariPoliKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnCariPoliActionPerformed(null);
        }
    }//GEN-LAST:event_BtnCariPoliKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnCari;
    private widget.Button BtnCariPoli;
    private widget.Button BtnKeluar;
    private widget.Tanggal DTPCari1;
    private widget.TextField KdPoli;
    private widget.TextField NmPoli;
    private widget.ScrollPane Scroll;
    private widget.TextField TCari;
    private widget.Label jLabel14;
    private widget.Label jLabel15;
    private widget.Label jLabel16;
    private widget.Panel panelBawah;
    private widget.Table tbDokter;
    // End of variables declaration//GEN-END:variables

    private void tampil() {
        if (!isLoading) {
            isLoading = true;
            Valid.tabelKosongSmc(tabMode);
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            final String kodePoli = KdPoli.getText().trim();
            final String cari = TCari.getText().trim();

            new SwingWorker<Void, Object[]>() {
                private volatile int i = 0;
                private String pesan = null;

                @Override
                protected Void doInBackground() throws Exception {
                    HttpHeaders headers = new HttpHeaders();
                    String utc = api.getUTCDateTimeAsString();
                    headers.setContentType(MediaType.APPLICATION_JSON);
                    headers.add("X-Cons-ID", koneksiDB.CONSIDAPIBPJS());
                    headers.add("X-Timestamp", utc);
                    headers.add("X-Signature", api.getHmac(utc));
                    headers.add("user_key", koneksiDB.USERKEYAPIBPJS());

                    final ObjectMapper mapper = new ObjectMapper();
                    JsonNode root = mapper.readTree(api.getRest().exchange(
                        koneksiDB.URLAPIBPJS() + "/referensi/dokter/pelayanan/2/tglPelayanan/" + Valid.getTglSmc(DTPCari1) + "/Spesialis/" + kodePoli,
                        HttpMethod.GET, new HttpEntity(headers), String.class).getBody());
                    JsonNode metadata = root.path("metaData");

                    if (metadata.path("code").asText().equals("200")) {
                        JsonNode response = mapper.readTree(api.Decrypt(root.path("response").asText(), utc));
                        if (response.path("list").isArray()) {
                            StreamSupport.stream(response.path("list").spliterator(), false)
                                .filter(list -> list.path("kode").asText().toLowerCase().contains(cari.toLowerCase()) || list.path("nama").asText().toLowerCase().contains(cari.toLowerCase()))
                                .forEach(list -> publish(new Object[] {
                                    (++i), list.path("kode").asText(), list.path("nama").asText()
                                }));
                        }
                    } else {
                        pesan = metadata.path("message").asText("");
                    }

                    return null;
                }

                @Override
                protected void process(List<Object[]> chunks) {
                    chunks.forEach(tabMode::addRow);
                }

                @Override
                protected void done() {
                    try {
                        get();
                        if (pesan != null) {
                            Valid.popupPeringatanDialog(pesan);
                        }
                    } catch (Exception e) {
                        System.out.println("Notif : " + e);
                        if (e.toString().contains("UnknownHostException")) {
                            Valid.popupInfoDialog("Koneksi ke server BPJS terputus...!");
                        }
                    }
                    BPJSReferensiDokter.this.setCursor(Cursor.getDefaultCursor());
                    isLoading = false;
                }
            }.execute();
        }
    }

    public void setPoli(String kodepoli, String namapoli) {
        KdPoli.setText(kodepoli);
        NmPoli.setText(namapoli);
        isOpened = false;
    }

    public boolean hasSelection() {
        return tbDokter.getSelectedRow() >= 0;
    }

    public Object getSelectedRow(int column) {
        return tbDokter.getValueAt(tbDokter.getSelectedRow(), column);
    }

    public JTable getTable() {
        return tbDokter;
    }
}
