/*
  Dilarang keras menggandakan/mengcopy/menyebarkan/membajak/mendecompile
  Software ini dalam bentuk apapun tanpa seijin pembuat software
  (Khanza.Soft Media). Bagi yang sengaja membajak softaware ini ta
  npa ijin, kami sumpahi sial 1000 turunan, miskin sampai 500 turu
  nan. Selalu mendapat kecelakaan sampai 400 turunan. Anak pertama
  nya cacat tidak punya kaki sampai 300 turunan. Susah cari jodoh
  sampai umur 50 tahun sampai 200 turunan. Ya Alloh maafkan kami
  karena telah berdoa buruk, semua ini kami lakukan karena kami ti
  dak pernah rela karya kami dibajak tanpa ijin.
 */
package bridging;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import fungsi.koneksiDB;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import fungsi.validasi;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.stream.StreamSupport;
import javax.swing.SwingWorker;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;

/**
 *
 * @author dosen
 */
public final class BPJSReferensiPoli extends widget.Dialog {
    private final DefaultTableModel tabMode;
    private final validasi Valid = new validasi();
    private final ApiBPJS api = new ApiBPJS();
    private volatile boolean isLoading = false;
    private boolean isOpened = false;

    /**
     * Creates new form DlgKamar
     *
     * @param parent
     * @param modal
     */
    public BPJSReferensiPoli(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        tabMode = new DefaultTableModel(null, new String[] {"No.", "Kode Poli", "Nama Poli"}) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        tbPoli.setModel(tabMode);

        for (int i = 0; i < 3; i++) {
            TableColumn column = tbPoli.getColumnModel().getColumn(i);
            if (i == 0) {
                column.setPreferredWidth(40);
            } else if (i == 1) {
                column.setPreferredWidth(140);
            } else if (i == 2) {
                column.setPreferredWidth(470);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Scroll = new widget.ScrollPane();
        tbPoli = new widget.Table();
        panelGlass6 = new widget.Panel();
        BtnKeluar = new widget.Button();
        jLabel16 = new widget.Label();
        TCari = new widget.TextField();
        BtnCari = new widget.Button();
        jLabel17 = new widget.Label();

        setIconImage(null);
        setIconImages(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        tbPoli.setAutoCreateRowSorter(true);
        tbPoli.setName("tbPoli"); // NOI18N
        tbPoli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbPoliMouseReleased(evt);
            }
        });
        Scroll.setViewportView(tbPoli);

        getContentPane().add(Scroll, java.awt.BorderLayout.CENTER);

        panelGlass6.setName("panelGlass6"); // NOI18N
        panelGlass6.setPreferredSize(new java.awt.Dimension(44, 68));
        panelGlass6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        BtnKeluar.setBackground(new java.awt.Color(255, 255, 255));
        BtnKeluar.setForeground(new java.awt.Color(255, 23, 26));
        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/exit.png"))); // NOI18N
        BtnKeluar.setText("KELUAR");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        panelGlass6.add(BtnKeluar);

        jLabel16.setText("Key word :");
        jLabel16.setName("jLabel16"); // NOI18N
        jLabel16.setPreferredSize(new java.awt.Dimension(110, 36));
        panelGlass6.add(jLabel16);

        TCari.setName("TCari"); // NOI18N
        TCari.setPreferredSize(new java.awt.Dimension(400, 36));
        TCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCariKeyPressed(evt);
            }
        });
        panelGlass6.add(TCari);

        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari.setMnemonic('6');
        BtnCari.setToolTipText("Alt+6");
        BtnCari.setName("BtnCari"); // NOI18N
        BtnCari.setPreferredSize(new java.awt.Dimension(36, 36));
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        BtnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariKeyPressed(evt);
            }
        });
        panelGlass6.add(BtnCari);

        jLabel17.setName("jLabel17"); // NOI18N
        jLabel17.setPreferredSize(new java.awt.Dimension(40, 23));
        panelGlass6.add(jLabel17);

        getContentPane().add(panelGlass6, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BtnCariActionPerformed(null);
        }
    }//GEN-LAST:event_TCariKeyPressed

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
        if (TCari.getText().isBlank()) {
            Valid.popupInfoDialog("Silahkan masukkan pencarian terlebih dahulu..!!!");
        } else {
            tampil();
        }
    }//GEN-LAST:event_BtnCariActionPerformed

    private void BtnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnCariActionPerformed(null);
        }
    }//GEN-LAST:event_BtnCariKeyPressed

    private void tbPoliMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPoliMouseReleased
        isOpened = false;
        dispose();
    }//GEN-LAST:event_tbPoliMouseReleased

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        isOpened = false;
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (!isOpened) {
            BtnCariActionPerformed(null);
            isOpened = true;
        }
    }//GEN-LAST:event_formWindowActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnCari;
    private widget.Button BtnKeluar;
    private widget.ScrollPane Scroll;
    private widget.TextField TCari;
    private widget.Label jLabel16;
    private widget.Label jLabel17;
    private widget.Panel panelGlass6;
    private widget.Table tbPoli;
    // End of variables declaration//GEN-END:variables

    private void tampil() {
        if (!isLoading) {
            isLoading = true;
            Valid.tabelKosongSmc(tabMode);
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            final String cari = TCari.getText().trim();

            new SwingWorker<Void, Object[]>() {
                private volatile int i = 0;
                private String pesan = null;

                @Override
                protected Void doInBackground() throws Exception {
                    HttpHeaders headers = new HttpHeaders();
                    String utc = api.getUTCDateTimeAsString();
                    headers.setContentType(MediaType.APPLICATION_JSON);
                    headers.add("X-Cons-ID", koneksiDB.CONSIDAPIBPJS());
                    headers.add("X-Timestamp", utc);
                    headers.add("X-Signature", api.getHmac(utc));
                    headers.add("user_key", koneksiDB.USERKEYAPIBPJS());

                    final ObjectMapper mapper = new ObjectMapper();
                    JsonNode root = mapper.readTree(api.getRest().exchange(
                        koneksiDB.URLAPIBPJS() + "/referensi/poli/" + cari,
                        HttpMethod.GET, new HttpEntity(headers), String.class).getBody());
                    JsonNode metadata = root.path("metaData");

                    if (metadata.path("code").asText().equals("200")) {
                        JsonNode response = mapper.readTree(api.Decrypt(root.path("response").asText(), utc));
                        if (response.path("poli").isArray()) {
                            StreamSupport.stream(response.path("poli").spliterator(), false)
                                .forEach(list -> publish(new Object[] {
                                    (++i), list.path("kode").asText(), list.path("nama").asText()
                                }));
                        }
                    } else {
                        pesan = metadata.path("message").asText("");
                    }

                    return null;
                }

                @Override
                protected void process(List<Object[]> chunks) {
                    chunks.forEach(tabMode::addRow);
                }

                @Override
                protected void done() {
                    try {
                        get();
                        if (pesan != null) {
                            Valid.popupPeringatanDialog(pesan);
                        }
                    } catch (Exception e) {
                        System.out.println("Notif : " + e);
                        if (e.toString().contains("UnknownHostException")) {
                            Valid.popupInfoDialog("Koneksi ke server BPJS terputus...!");
                        }
                    }
                    BPJSReferensiPoli.this.setCursor(Cursor.getDefaultCursor());
                    isLoading = false;
                }
            }.execute();
        }
    }

    public boolean hasSelection() {
        return tbPoli.getSelectedRow() >= 0;
    }

    public Object getSelectedRow(int column) {
        return tbPoli.getValueAt(tbPoli.getSelectedRow(), column);
    }

    public JTable getTable() {
        return tbPoli;
    }
}
