/*
  Dilarang keras menggandakan/mengcopy/menyebarkan/membajak/mendecompile
  Software ini dalam bentuk apapun tanpa seijin pembuat software
  (Khanza.Soft Media). Bagi yang sengaja membajak softaware ini ta
  npa ijin, kami sumpahi sial 1000 turunan, miskin sampai 500 turu
  nan. Selalu mendapat kecelakaan sampai 400 turunan. Anak pertama
  nya cacat tidak punya kaki sampai 300 turunan. Susah cari jodoh
  sampai umur 50 tahun sampai 200 turunan. Ya Alloh maafkan kami
  karena telah berdoa buruk, semua ini kami lakukan karena kami ti
  dak pernah rela karya kami dibajak tanpa ijin.
 */
package bridging;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import fungsi.validasi;
import fungsi.koneksiDB;
import java.awt.Cursor;
import java.util.List;
import java.util.stream.StreamSupport;
import javax.swing.SwingWorker;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;

/**
 *
 * @author dosen
 */
public final class BPJSRiwayatRujukanPasien extends widget.Dialog {
    private final DefaultTableModel tabMode;
    private final ApiBPJS api = new ApiBPJS();
    private final validasi Valid = new validasi();
    private volatile boolean isLoading = false;
    private boolean isOpened = false;

    /**
     * Creates new form DlgKamar
     *
     * @param parent
     * @param modal
     */
    public BPJSRiwayatRujukanPasien(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        tabMode = new DefaultTableModel(null, new Object[] {
            "Kode Diagnosa", "Nama Diagnosa", "No. Rujukan", "Kode Tujuan", "Nama Tujuan", "Tgl. Rujukan", "Kode PPK", "Nama PPK", "Status"
        }) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        tbRiwayat.setModel(tabMode);

        for (int i = 0; i < 9; i++) {
            TableColumn column = tbRiwayat.getColumnModel().getColumn(i);
            if (i == 0) {
                column.setPreferredWidth(60);
            } else if (i == 1) {
                column.setPreferredWidth(160);
            } else if (i == 2) {
                column.setPreferredWidth(200);
            } else if (i == 3) {
                column.setPreferredWidth(70);
            } else if (i == 4) {
                column.setPreferredWidth(200);
            } else if (i == 5) {
                column.setPreferredWidth(150);
            } else if (i == 6) {
                column.setPreferredWidth(150);
            } else if (i == 7) {
                column.setPreferredWidth(160);
            } else if (i == 8) {
                column.setPreferredWidth(100);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Scroll = new widget.ScrollPane();
        tbRiwayat = new widget.Table();
        panelBawah = new widget.Panel();
        BtnKeluar = new widget.Button();
        jLabel16 = new widget.Label();
        noPeserta = new widget.TextField();
        namaPasien = new widget.TextField();
        jLabel17 = new widget.Label();

        setIconImage(null);
        setIconImages(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        tbRiwayat.setToolTipText("Silahkan klik untuk memilih data yang mau diedit ataupun dihapus");
        tbRiwayat.setName("tbRiwayat"); // NOI18N
        tbRiwayat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbRiwayatMouseReleased(evt);
            }
        });
        Scroll.setViewportView(tbRiwayat);

        getContentPane().add(Scroll, java.awt.BorderLayout.CENTER);

        panelBawah.setName("panelBawah"); // NOI18N
        panelBawah.setPreferredSize(new java.awt.Dimension(44, 68));
        panelBawah.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        BtnKeluar.setBackground(new java.awt.Color(255, 255, 255));
        BtnKeluar.setForeground(new java.awt.Color(255, 23, 26));
        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/exit.png"))); // NOI18N
        BtnKeluar.setText("KELUAR");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        panelBawah.add(BtnKeluar);

        jLabel16.setText("Pasien :");
        jLabel16.setName("jLabel16"); // NOI18N
        jLabel16.setPreferredSize(new java.awt.Dimension(90, 36));
        panelBawah.add(jLabel16);

        noPeserta.setEditable(false);
        noPeserta.setName("noPeserta"); // NOI18N
        noPeserta.setPreferredSize(new java.awt.Dimension(200, 36));
        panelBawah.add(noPeserta);

        namaPasien.setEditable(false);
        namaPasien.setName("namaPasien"); // NOI18N
        namaPasien.setPreferredSize(new java.awt.Dimension(450, 36));
        panelBawah.add(namaPasien);

        jLabel17.setFocusable(false);
        jLabel17.setName("jLabel17"); // NOI18N
        jLabel17.setPreferredSize(new java.awt.Dimension(30, 23));
        panelBawah.add(jLabel17);

        getContentPane().add(panelBawah, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void tbRiwayatMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRiwayatMouseReleased
        dispose();
    }//GEN-LAST:event_tbRiwayatMouseReleased

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (!isOpened) {
            tampil();
            isOpened = true;
        }
    }//GEN-LAST:event_formWindowActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnKeluar;
    private widget.ScrollPane Scroll;
    private widget.Label jLabel16;
    private widget.Label jLabel17;
    private widget.TextField namaPasien;
    private widget.TextField noPeserta;
    private widget.Panel panelBawah;
    private widget.Table tbRiwayat;
    // End of variables declaration//GEN-END:variables

    public void tampil() {
        if (!isLoading) {
            isLoading = true;
            Valid.tabelKosongSmc(tabMode);
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

            new SwingWorker<Void, Object[]>() {
                private final String noPeserta = BPJSRiwayatRujukanPasien.this.noPeserta.getText();
                private String pesan = null;

                @Override
                protected Void doInBackground() throws Exception {
                    HttpHeaders headers = new HttpHeaders();
                    String utc = api.getUTCDateTimeAsString();
                    headers.setContentType(MediaType.APPLICATION_JSON);
                    headers.add("X-Cons-ID", koneksiDB.CONSIDAPIBPJS());
                    headers.add("X-Timestamp", utc);
                    headers.add("X-Signature", api.getHmac(utc));
                    headers.add("user_key", koneksiDB.USERKEYAPIBPJS());

                    final ObjectMapper mapper = new ObjectMapper();
                    JsonNode root = mapper.readTree(api.getRest().exchange(
                        koneksiDB.URLAPIBPJS() + "/Rujukan/List/Peserta/" + noPeserta,
                        HttpMethod.GET, new HttpEntity(headers), String.class).getBody());
                    JsonNode metadata = root.path("metaData");

                    if (metadata.path("code").asText().equals("200")) {
                        JsonNode response = mapper.readTree(api.Decrypt(root.path("response").asText(), utc));
                        if (response.path("rujukan").isArray()) {
                            StreamSupport.stream(response.path("rujukan").spliterator(), false)
                                .forEach(list -> publish(new Object[] {
                                    list.path("diagnosa").path("kode").asText(), list.path("diagnosa").path("nama").asText(), list.path("noKunjungan").asText(),
                                    list.path("poliRujukan").path("kode").asText(), list.path("poliRujukan").path("nama").asText(), list.path("tglKunjungan").asText(),
                                    list.path("provPerujuk").path("kode").asText(), list.path("provPerujuk").path("nama").asText(), "FKTP"
                                }));
                        }
                    } else {
                        pesan = metadata.path("message").asText("");
                    }

                    headers = new HttpHeaders();
                    utc = api.getUTCDateTimeAsString();
                    headers.setContentType(MediaType.APPLICATION_JSON);
                    headers.add("X-Cons-ID", koneksiDB.CONSIDAPIBPJS());
                    headers.add("X-Timestamp", utc);
                    headers.add("X-Signature", api.getHmac(utc));
                    headers.add("user_key", koneksiDB.USERKEYAPIBPJS());

                    root = mapper.readTree(api.getRest().exchange(
                        koneksiDB.URLAPIBPJS() + "/Rujukan/RS/List/Peserta/" + noPeserta,
                        HttpMethod.GET, new HttpEntity(headers), String.class).getBody());
                    metadata = root.path("metaData");

                    if (metadata.path("code").asText().equals("200")) {
                        JsonNode response = mapper.readTree(api.Decrypt(root.path("response").asText(), utc));
                        if (response.path("rujukan").isArray()) {
                            StreamSupport.stream(response.path("rujukan").spliterator(), false)
                                .forEach(list -> publish(new Object[] {
                                    list.path("diagnosa").path("kode").asText(), list.path("diagnosa").path("nama").asText(), list.path("noKunjungan").asText(),
                                    list.path("poliRujukan").path("kode").asText(), list.path("poliRujukan").path("nama").asText(), list.path("tglKunjungan").asText(),
                                    list.path("provPerujuk").path("kode").asText(), list.path("provPerujuk").path("nama").asText(), "FKTL"
                                }));
                        }
                    } else {
                        pesan = metadata.path("message").asText("");
                    }

                    return null;
                }

                @Override
                protected void process(List<Object[]> chunks) {
                    chunks.forEach(tabMode::addRow);
                }

                @Override
                protected void done() {
                    try {
                        get();
                        if (pesan != null) {
                            Valid.popupPeringatanDialog(pesan);
                        }
                    } catch (Exception e) {
                        System.out.println("Notif : " + e);
                        if (e.toString().contains("UnknownHostException")) {
                            Valid.popupInfoDialog("Koneksi ke server BPJS terputus...!");
                        }
                    }
                    BPJSRiwayatRujukanPasien.this.setCursor(Cursor.getDefaultCursor());
                    isLoading = false;
                }
            }.execute();
        }
    }

    public void setPasien(String noPeserta, String namaPasien) {
        this.noPeserta.setText(noPeserta);
        this.namaPasien.setText(namaPasien);
        isOpened = false;
    }

    public boolean hasSelection() {
        return tbRiwayat.getSelectedRow() >= 0;
    }

    public Object getSelectedRow(int column) {
        return tbRiwayat.getValueAt(tbRiwayat.getSelectedRow(), column);
    }

    public JTable getTable() {
        return tbRiwayat;
    }
}
